### ISSUE TITLE
Save page as pdf

### ISSUE THREAD

**Issue by Gunkev** [mozilla-mobile/outreachy-UX-2020#102]
### What is the problem you are trying to solve?
Save page as pdf
### Why is it a problem?
As I was going through medium I found some interested articles instead of saving the whole website I just wanted to save some articles such that I could access them anytime later quickly when offline.
### How would you solve the problem? What is your design proposal?
As an Idea i will add a mechanism that permit user to save a page or even a whole website as PDF. Especially articles this will facilitate accessibility and usability

![save page as pdf](https://user-images.githubusercontent.com/36812576/78548658-0c96e880-77f9-11ea-9695-ef8e4d12d736.png)

### How would you measure your designs effectiveness?
1. I will consider my effectiveness base on user need and experience. Working with a group of user will help me understand what the want and in which for the want it.

**Comment by moonlit** [comment]
"Save as PDF" exists in the current stable version of Firefox for Android and Mozilla Firefox for Android will not be a reasonable alternative until it has been added.
