### ISSUE TITLE
 Voice input for Search #1216 - Fisa

### ISSUE THREAD

**Issue by FisaVuma** [mozilla-mobile/outreachy-UX-2020#18]
### What is the problem you are trying to solve?
Accents, pronunciation issues with voice search

### Why is it a problem?
I did a research working with the visually impaired, I noticed issues when it came to mobile understanding different accents and pronunciations and users not getting results
And also the user at times does not understand the voice output, adding this option in browser could also provide added security and customer stickiness

### How would you solve the problem? What is your design proposal?
1. Voice training and transcribing — Accept different voice inputs from user during initial setup to train and adapt, providing automatic speech recognition, taking in audio and automatically generates accurate transcripts.

2. Translate — setup a neural machine-translation service for language translation. This can be optional

3. Provide feedback in text-to-speech, synthesize speech that sounds like the user's voice and default language

### How would you measure your designs effectiveness?
User feedback - since the solution should adapt to user voice, accuracy is key
Carry out performance tests, check for processing time and resource utilization

**Comment by topotropic** [comment]
Thanks for your contribution. Reminds me of [https://voice.mozilla.org/en](https://voice.mozilla.org/en)
