### ISSUE TITLE
Swipe Left/ Right to Navigate #3481 #176

### ISSUE THREAD

**Issue by areeshatariq** [mozilla-mobile/outreachy-UX-2020#19]
### What is the problem you are trying to solve?
The support for the gesture of swiping left or right on the URL address bar to switch tabs
[#3481](https://github.com/mozilla-mobile/fenix/issues/3481) Switch Tabs via Swiping Address Bar
[#176](https://github.com/mozilla-mobile/fenix/issues/176) Gestures -  Swipe left/right to navigate
### Why is it a problem?
Currently, to switch to a previous or next tab, the user is directed to the homepage where all the opened tabs can be seen. The user can open the previous tab from the list of 'Open tabs'. This process requires at least two taps. This problem should be addressed to make the application a bit inclusive towards people who might have some difficulty in tapping every time while switching the tabs.
### How would you solve the problem? What is your design proposal?
The support for the following gestures would be added:
- Swipe right on the URL address bar to open the previous tab
- Swipe left on the URL address bar to open the next tab

## Design
As the user swipes right on the URL address bar, the current tab moves right and this way the previous tab can be opened.
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/76861935-2b9bfd80-687f-11ea-9baf-7a5f0486a5ce.png" width="50%" height="50%"></p>

### How would you measure your designs effectiveness?
By testing the feature on a group of people from the team and taking their reviews about it.

**Comment by topotropic** [comment]
Yes! I hope this will be implemented.
