### ISSUE TITLE
Swipe Left/ Right to Delete 

### ISSUE THREAD

**Issue by areeshatariq** [mozilla-mobile/outreachy-UX-2020#20]
### What is the problem you are trying to solve?
[#176](https://github.com/mozilla-mobile/fenix/issues/176) Gestures - Swipe left/right to delete
- Swipe left/right on a bookmark entry to delete
- Swipe left/right on a history entry to delete

### Why is it a problem?
Currently, to delete an item from bookmarks or history, the user has to click on the vertical ellipses and click on the Delete option from the drop-down. This process requires at least two taps. This problem should be addressed to make the application a bit inclusive towards people who might have some difficulty in tapping to delete an item from bookmarks/ history.
### How would you solve the problem? What is your design proposal?
The support the following gesture would be added:
- Swipe left or right to delete an item from Bookmarks
- Swipe left or right to delete an item from History
### Design
When the user starts swiping on a  library item, the action is revealed and the user can either swipe to delete or stop to keep the item.
#### Bookmarks
When the user swipes the item to right:
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/76865226-3907b680-6884-11ea-9fd0-0052e3ca2ff2.png" width="50%" height="50%"></p>
When the user swipes the item to left:
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/76865237-3d33d400-6884-11ea-95cd-31cd8c6e6171.png" width="50%" height="50%"></p>

#### History
When the user swipes the item to right:
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/76865511-a582b580-6884-11ea-89f2-9c6873097b4e.png" width="50%" height="50%"></p>
When the user swipes the item to left:
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/76865519-a87da600-6884-11ea-8fdb-7f1d3d99df40.png" width="50%" height="50%"></p>

### How would you measure your designs effectiveness?
By testing the feature on a group of people from the team and taking their reviews about it. User's reviews will help in working iteratively to improve the design.

**Comment by topotropic** [comment]
Thanks for the contribution.
