### ISSUE TITLE
Enhanced Search Experience - Rupali

### ISSUE THREAD

**Issue by Rupali2412** [mozilla-mobile/outreachy-UX-2020#21]
### What is the problem you are trying to solve?
Enhanced Search Experience Issue

### Why is it a problem? (Why is it important)
Enhancing Search experience is essential as it is one of the most common elements that we interact with daily. If users can easily express their queries and needs, and they get useful information or personalised information, it can be a win for the app or website.

### How would you solve the problem? What is your design proposal?
We can enhance the user’s searching experience by : 
**1. Improving the search experience on the home screen**

**- Providing upfront search engines** - One-touch search can be provided on the home screen for some website and QR scanning feature. 
Also, The search widget on the home screen is always searching on google.
![1](https://user-images.githubusercontent.com/60149380/76884293-80516f80-68a3-11ea-9985-c02d6ef3170d.png)

**- Search widget** - Search Widget and + button both performs the same function in the home screen. 
The + button. can be replaced by voice search which will be used some search engine. 
![2](https://user-images.githubusercontent.com/60149380/76884306-86dfe700-68a3-11ea-92d5-1c04e1e7a0ae.png)

**2. Taking references from history searches** 

**-Search History and Bookmarks** - A search bar can be provided in history and bookmarks so that user can search through history easily without scrolling. 
![3](https://user-images.githubusercontent.com/60149380/76885701-a546e200-68a5-11ea-91fb-8268b02acd3e.png)

**-Predictive Recommendations and Personalisation based on past searches** 
Recommendations in awesome bar can be of the website visited in past.

### How would you measure your design's effectiveness?
1. A/B testing - I can do a quick A/B with my classmates (belongs to a major user base of the internet) with modified wireframe prototyping.
2. Observing Competitors - Comparing the feature with direct competitors and analysing the user experience throughout both the products, then modifying the experience.

**Comment by topotropic** [comment]
Thanks for the contribution – the voice search is smart!
