### ISSUE TITLE
design issues in Firefox Preview

### ISSUE THREAD

**Issue by sunidhi-kashyap** [mozilla-mobile/outreachy-UX-2020#22]
### Name the three biggest issues
1. Recently opened tabs are displayed in list view format. And this format has
many disadvantages here. 
![Group 1](https://user-images.githubusercontent.com/42182441/76895343-d0393200-68b5-11ea-87ca-edfd0758d6e3.jpg)

2. After selecting a search engine, the user needs to go back to the previous page to switch to another search engine.
![Group 5 (1)](https://user-images.githubusercontent.com/42182441/76895455-0a0a3880-68b6-11ea-8484-bad260121c27.jpg)

3. The search bar and the + button perform the same task.

### Explain why it’s an issue 
1. a) The elements looks too cluttered to the user.
    b) User's attention decreases from top to bottom.
    c) Less information is displayed per page.

2. Going back and forth to the same page for switching is frustrating.

3. A button exists that takes up space and energy but does not perform a significant role.

### Show us how you would improve it

soln to issue 1:
Use of grid view instead of list view. And reduction of unnecessary text.

soln to issue 2:
After selecting a search engine, the list of all the search engine remains there, so the user can switch.

soln to issue 3:
+ button must be replaced by the "collections" button.

### How would you measure your designs effectiveness?
Effectiveness per solution explained: 

soln 1:
The elements don't look cluttered anymore.
Even though the text will be less, since it is a list of "recent tabs", the user will recognize the page just by that little information.

soln 2:
The user won't be frustrated easily as less clicks will be required to switch.

soln 3:

The extra space used by "collections" section in the home page will be removed.

My work approach :

![IMG_20200317_224141](https://user-images.githubusercontent.com/42182441/76896313-9f59fc80-68b7-11ea-8b90-69efad501100.jpg)

![IMG_20200317_224152](https://user-images.githubusercontent.com/42182441/76896345-a97bfb00-68b7-11ea-8aa5-f6d0ae7702d1.jpg)

**Comment by topotropic** [comment]
Thanks for your feedback – I really like the sketches!

If you have time, could you open an issue in the [Firefox Preview repository](https://github.com/mozilla-mobile/fenix/issues) to address this: 

>     2\. After selecting a search engine, the user needs to go back to the previous page to switch to another search engine.

Thank you!

**Comment by sunidhi-kashyap** [comment]
Thanks for the response.

Sure I'll do it by today itself.

**Comment by sunidhi-kashyap** [comment]
Hey Nicole,

I opened the issue as you said.

https://github.com/mozilla-mobile/fenix/issues/9650

P.S. Thanks for the appreciation!

Thankyou
