### ISSUE TITLE
Past Work - Mockups of an E-learning Mobile App Using Adobe Xd

### ISSUE THREAD

**Issue by lkmandy** [mozilla-mobile/outreachy-UX-2020#23]
Find below mockups of the main screens of an e-learning mobile application made using Adobe Xd. 
[Link to mockups](https://xd.adobe.com/view/2c16e887-1555-4411-61b9-7a6fdd273a5a-5a27/grid/)

![kuva splash screen](https://user-images.githubusercontent.com/17765231/76923950-32555f80-68d5-11ea-98f3-40a7db167b75.png)

**Comment by topotropic** [comment]
Awesome, thanks for sharing!
