### ISSUE TITLE
Past Work- Digital design portfolio-Riya

### ISSUE THREAD

**Issue by riyasoganii** [mozilla-mobile/outreachy-UX-2020#24]
Please find the link to my past work in digital design- Using Adobe photoshop, Adobe illustrator, Adobe Sketch, etc.
https://drive.google.com/drive/folders/1v62vBSjkl996PwnWVOu8-S9b0oznbC7g?usp=sharing
or check out my full portfolio at:
https://www.behance.net/riyasoganii

**Comment by topotropic** [comment]
Thanks for sharing!
