### ISSUE TITLE
Past projects working with Moodle- Fisa

### ISSUE THREAD

**Issue by FisaVuma** [mozilla-mobile/outreachy-UX-2020#25]
In 2015, I had the opportunity to be part of the e-learning workshop for Institute of Public Health (India) in collaboration with Institute of Tropical Medicine (Belgium) blended learning titled “Get Started, Keep Moving”

The main purpose of the workshop was to educate the participants on planning, designing and implementing distance learning modules through collaborations using Moodle, which is a free e-learning software. Any changes and contributions were done as a team with participants from different parts of the world.

Links:
https://iphindia.org/events/2015-events/e-learning-workshop-2015/
See Participants from Zimbabwe option

http://zihat.itg.be/login/index.php

**Comment by topotropic** [comment]
Thanks for sharing!
