### ISSUE TITLE
Three issues I found while using Firefox Preview

### ISSUE THREAD

**Issue by RQWorldblender** [mozilla-mobile/outreachy-UX-2020#26]
### Name the three biggest issues
1. Can't import data from at least Firefox for Android, except for Firefox account.
2. Can only clear the entire time period of browsing data, not from smaller time ranges or specific domains like on desktop Firefox.
3. No "Work Offline" functionality like on desktop Firefox to read webpages even without an internet connection.

The latter two issues also apply to the current Firefox for Android.

### Explain why it’s an issue 
1. It makes it harder for users switching from other browsers or the current Firefox for Android to easily migrate to Firefox Preview without having to start from scratch.
2. Sometimes clearing the data of, for example, trackers, but not visited websites, is more useful to do. Clearing only more recent or oldest data is also useful for tidying up browsing data without going full nuclear.
3. In case internet connection is lost, users may be unable to read cached webpages until they can get an internet connection again.

### Show us how you would improve it
1. Add a settings page that allows for importing data from at least Firefox for Android, and what kind of data to be imported. Note that doing this for other browsers may require additional security permissions on more recent Android versions.
2. Expand the "Delete browsing data" page to include a slider or dropdown list indicating a time range to delete browsing data from. When deleting browsing data, only delete within the time range specified earlier.
3. Add the ability for at least one of the following:
    * Add an option to save active webpage as HTML or PDF (the latter already being implemented in Firefox for Android). Specifying the download directory is optional.
    * Add on option to work offline, by forcing Firefox Preview to not use active internet connections, and to load webpages only from cache.

### How would you measure your designs effectiveness?
1. The imported data (history, open tabs, cookies, etc.) successfully appears in Firefox Preview.
2. If a specific time range is selected, after deletion, the browsing data outside of the specified time range is not entirely erased.
3. Depends on which option(s) are implemented:
    * An HTML (HTML + directory containing additional files) file or PDF file is saved to either the "Download" directory, or the user-specified directory.
    * Cached webpages are successfully loaded instead of an error message appearing in place, unless a webpage specifies not to be saved in cache.

**Comment by topotropic** [comment]
Thanks for the contribution!

I'd be curios to see a quick sketch or visualization for the following if you have time:

> * Expand the "Delete browsing data" page to include a slider or dropdown list indicating a time range to delete browsing data from. When deleting browsing data, only delete within the time range specified earlier.
> 
> * Add the ability for at least one of the following:
>   
>   * Add an option to save active webpage as HTML or PDF (the latter already being implemented in Firefox for Android). Specifying the download directory is optional.
>   * Add on option to work offline, by forcing Firefox Preview to not use active internet connections, and to load webpages only from cache.

Very much appreciated!
