### ISSUE TITLE
Add Text to Speech Feature to Reader Mode

### ISSUE THREAD

**Issue by areeshatariq** [mozilla-mobile/outreachy-UX-2020#27]
### What is the problem you are trying to solve?
[#1273](https://github.com/mozilla-mobile/fenix/issues/1273) Add narration feature to Reader Mode 
### Why is it a problem?
- Since the text-to-speech feature is currently not implemented, this makes it difficult for people who are visually impaired to use the application. Adding the text-to-speech feature in the application will make it more inclusive towards people who are visually impaired. 
- Making digital content accessible in multiple forms can create a better user experience. Text to speech feature will open doors to anyone looking for easier ways to access digital content.
- Text to speech feature will give access to the content to a greater population, such as those with literacy difficulties, learning disabilities, reduced vision. 
### How would you solve the problem? What is your design proposal?
- Text to Speech (TTS) icon will be added on the toolbar when the Reader mode is enabled.
- Once the user clicks on the TTS icon, it will start reading from the beginning.
- The text being read by TTS will be highlighted.
- The user can highlight text to read only the highlighted text.
- The TTS icon will disappear when the Reader Mode is disabled
#### Design
Text to Speech (TTS) icon is added on the toolbar when the Reader mode is enabled
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77004114-620d7180-6980-11ea-93c0-dbde828e82c8.png" width="50%" height="50%"></p>

The text being read by TTS will be highlighted
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77004221-8f5a1f80-6980-11ea-95c9-90cd1d0dc956.png" width="50%" height="50%"></p>

When a user highlights text, a pop-up appears with TTS icon which can be clicked to read text
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77007300-c979f000-6985-11ea-89a6-9156016585fe.png" width="50%" height="50%"></p>

### How would you measure your designs effectiveness?
- By testing the feature on a group of users including people who are visually impaired and taking their reviews about the feature
- Comparing user experience with the competitors

**Comment by topotropic** [comment]
Thanks for the contribution! 

A quick follow up question: How would you enable/disable reader mode?

**Comment by areeshatariq** [comment]
@topotropic it will be enabled/ disabled in the same way as it is currently done in the application. By clicking on the three vertical ellipses and then clicking on the toggle button, the user can enable/ disable the reader mode.
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/78297922-0fb87d00-754a-11ea-9be9-615eef6c3ec4.jpeg" width="50%" height="50%"></p>
