### ISSUE TITLE
Learn about other Fx Products #4634 - Abigail

### ISSUE THREAD

**Issue by abigail-makolo** [mozilla-mobile/outreachy-UX-2020#28]
### What is the problem you are trying to solve?
As a user, I want to be able to open the browser for the first time and easily find out about the advantages of having a Firefox Account.

### Why is it a problem?
The current appearance of the **Sign in section** on the welcome page does not really encourage a user to create an account. It also does not promote the use of other Fx products.

<img width="500" alt="Screenshot 2020-03-18 at 22 46 19" src="https://user-images.githubusercontent.com/57357223/77010566-4f883d80-696a-11ea-9900-d1a32a53c292.png">

### How would you solve the problem? What is your design proposal?

1. I would begin by understanding what a user's motivation should be for creating a Firefox account. I would outline those benefits (e.g. sync history, use other apps). Additionally, I would identify the other Fx products and think about how best to present them on the browser.

2. I would include a few benefits of creating or signing into a Firefox account on the welcome page. I would also include details about other Fx products and include a link to Learn more. I would visualize these ideas using a sketch as shown below:

![_4634 - Design proposal - Sketch - v1](https://user-images.githubusercontent.com/57357223/77013765-0daec580-6971-11ea-898a-de6718b9b009.png)

OR

![_4634 - Design proposal - Sketch - v2](https://user-images.githubusercontent.com/57357223/77013782-169f9700-6971-11ea-86b8-9c9b16f5831f.png)

3. Another option to increase Fx product presence on the browser would be to include a panel at the bottom of the welcome page featuring other Firefox products as illustrated below:

![_4634 - Design proposal - Sketch - v3](https://user-images.githubusercontent.com/57357223/77013951-7d24b500-6971-11ea-8286-f7d43aac71a5.png)

### How would you measure your design's effectiveness?

- I would measure how effective this design is by making an interactive prototype and testing that for usability with a sample of users (without priming) to see how many would be curious or interested in signing in to Firefox.

- If the design is implemented, I would measure effectiveness by analysing usage analytics to see how many users are now signing in or creating Firefox accounts after the design improvement.

This issue is based on [Issue #4634](https://github.com/mozilla-mobile/fenix/issues/4634)

**Comment by topotropic** [comment]
Thanks for the contribution. This is really well explained and easy to follow. 

I'd be curious to learn if you considered other places to introduce users to the Firefox product family despite the on-boarding cards.

**Comment by abigail-makolo** [comment]
Thank you for the feedback @topotropic.
Yes I had considered other options for where to introduce users to the Firefox product family. I have illustrated them below:

- The **Account Settings page** as that is where users might expect to find anything related to their Firefox account. There is also some space to accommodate this on that page.

- The **About section of the Settings page**. Since there is already an option there to learn more about Firefox Preview, there could also be one to learn about **Other Firefox Products**. It could also be presented with more captivating copy e.g. **"Do More with Firefox"**.

![image](https://user-images.githubusercontent.com/57357223/78303583-dc1f2800-7534-11ea-88ed-49d85e03bd03.png)

- The **What's New page** or the "Help page". When the user clicks on "Help" or "What's New" in the app menu, they get directed to a web page that explains new features on the app. Just at the bottom of that page could be some information about other Firefox products. This way, we could subtly present the idea that the user could explore other Firefox products.

![image](https://user-images.githubusercontent.com/57357223/78304243-31a80480-7536-11ea-95b7-9a407f1e0943.png)

- Another idea I had was having periodic prompts appear across the main screen showcasing one Firefox product at a time.

![image](https://user-images.githubusercontent.com/57357223/78305265-61580c00-7538-11ea-8265-fc790374fa2d.png)

I would be happy to further explore and discuss any of these ideas. 😊

**Comment by abigail-makolo** [comment]
There are also some contextual signifiers that could be used. For example, when Fenix detects a successful login or account creation on a web page it is serving, there could be a pop-up or prompt encouraging the user to use Lockwise to save their passwords securely.
