### ISSUE TITLE
firefox preview app design review- manishita choudhary

### ISSUE THREAD

**Issue by manishita24** [mozilla-mobile/outreachy-UX-2020#29]
### Name the three biggest issues
1. bottom search bar does not hide when scrolling
2. no option to undo a deletion of a tab from collection
3. deleting individual history tabs should be easier and faster

### Explain why it’s an issue 
issue 1: when scrolling the screen, if the search bar is placed in the bottom, it does not hide like the search bar when placed on top of the screen. This takes up unnecessary space when viewing the content of the screen. This feature is already implemented in firefox nightly for both top and bottom search bar.

issue 2: if any tab is deleted from a collection, there is no way to retrieve the tab back. the user has to add it manually again by opening a new tab, searching for the item and adding it again.

issue 3: when deleting the tabs one by one, the process would be very cumbersome and inefficient as the user has to first click the 3 dot menu and then deleting the tab. This is an unnecessary step as the user has to make an extra click.

### Show us how you would improve it
solution 1: when the user scrolls down the screen, the bottom search bar should automatically hide similarly to the top search bar. the down scroll acts as a trigger for hiding the search bar. Here is an example gif:

<img src="https://user-images.githubusercontent.com/60927308/77053619-9f134b80-69f4-11ea-9f3a-1c3f00840c6e.gif" width="350" height="623">

solution 2: as a user can delete a tab from collections accidentally, there should be a pop up with undo option which again adds the tab deleted back to the collection. This would save the user from again manually adding a tab to the collection. if the undo is not clicked, the pop up would disappear. Here is an example gif:

<img src="https://user-images.githubusercontent.com/60927308/77059613-367c9c80-69fd-11ea-9d0e-8cd6b1ca11dc.gif" width="350" height="623">

solution 3: a cross button should replace the 3 dot menu so as to save the extra unnecessary step of deleting tabs from history. this method is not only efficient but also faster as compared to the current 3 dot menu option. Here is an example gif:

<img src="https://user-images.githubusercontent.com/60927308/77055074-62485400-69f6-11ea-8011-10ceeeb04694.gif" width="350" height="623">

### How would you measure the effectiveness of your designs?
1. Effectiveness can be measured by comparing features to competitor web browsers as well as already existing successful products of firefox.
2. By getting feedbacks from fellow UI/UX designers.
3. The design would be effectively implemented if:
   a. The search bar hides when scrolling down the screen.
   b. The user is able to undo tab deletion from collections.
   c. User is able to delete history directly by clicking on the cross button

**Comment by topotropic** [comment]
Thanks for the feedback, I really like your example gifs!
