### ISSUE TITLE
Auto-fill address in form

### ISSUE THREAD

**Issue by Gunkev** [mozilla-mobile/outreachy-UX-2020#30]
### What is the problem you are trying to solve?
Auto-fill address on website

### Why is it a problem?
This is a problem cause each time a user wants to sign in in a website he is oblige to hard type his user or email. If user were to sign in or authenticate in more than 3 website this could be tiresome and time consuming since the Firefox preview does not propose default user or email which were used recently or used at least once.

### How would you solve the problem? What is your design proposal?
An idea is to propose algorithm that keeps tracks of recently used information excluding sensible ones or information that have been input at least once in order to fully propose some options to user for them to choice and save time. Below is a proposed mockup: A propose a list of information and the one which was recently used is auto-filled in the form field and B just proposes a list of information for users to choose

![autofill](https://user-images.githubusercontent.com/36812576/77102276-db58a300-6a18-11ea-9dcf-8fda62f7bf03.png)

### How would you measure your designs effectiveness?
I will measure first of all base on user user feedback. Another way is including user directly in the process and getting feedback directly each time

**Comment by topotropic** [comment]
Thanks, I like the visualization
