### ISSUE TITLE
Delete history websites directly from the address bar suggestions.-manishita 

### ISSUE THREAD

**Issue by manishita24** [mozilla-mobile/outreachy-UX-2020#32]
### What is the problem you are trying to solve?
Delete history websites directly from the address bar suggestions. https://github.com/mozilla-mobile/fenix/issues/1920#issue-436199092

### Why is it a problem?
While searching the user may have typed its search query wrong or the address is typed wrong.
But the search keeps on popping up in suggestions when typing a similar search query. 

### How would you solve the problem? What is your design proposal?
the user may want to delete these wrong/misspelled search queries which are unnecessarily popping up in the search suggestions.
solution: such entries could be deleted by a small cross button placed at the end of these search query tabs. 
Design proposal: here is an example gif:

<img src="https://user-images.githubusercontent.com/60927308/77167323-d577c600-6adb-11ea-91c9-d03035ecef76.gif" width="350" height="623">

### How would you measure the effectiveness of your designs?
the design would be successfully implemented when the user is able to delete search suggestions from search bar when typing a similar query bu tapping on the cross button placed at the end

**Comment by topotropic** [comment]
Thanks for the gif, looks good! 

Would your solution also delete the history item? Do you think it would be clear enough to users what the impact is of tapping on x is?

**Comment by manishita24** [comment]
thanks for the feedback. yes clicking on the x would delete the item from history as well. As this feature is also generally available for most delete related activities, the user would be able to identify the impact of tapping on x.
