### ISSUE TITLE
Firefox Preview App Review-Advika Singh

### ISSUE THREAD

**Issue by adi-1999** [mozilla-mobile/outreachy-UX-2020#33]
### Name the three biggest issues
1. There are 2 scan options when you start using the app. One is present when you go to the settings and one near the search option. However, the later one doesn't give any instructions as to what to do. 
![WhatsApp Image 2020-03-20 at 11 16 10 PM (1)](https://user-images.githubusercontent.com/58343952/77199141-5cde2d00-6b0e-11ea-971c-a73c7dc0e8a3.jpeg)
![WhatsApp Image 2020-03-20 at 11 16 10 PM](https://user-images.githubusercontent.com/58343952/77199146-5e0f5a00-6b0e-11ea-8534-91e90856643b.jpeg)
2.  The search bar and the "+" sign right next to it perform the same functions. 
3.   In some websites when you switch on the desktop site the page doesn't fit on the screen of the mobile. 
![WhatsApp Image 2020-03-21 at 1 22 30 AM](https://user-images.githubusercontent.com/58343952/77201477-8bf69d80-6b12-11ea-8463-27deb01eb8d4.jpeg)

 
 ### Explain why it’s an issue 
1) There are no instructions as to how to operate the scanner. The user is not informed about how to use the scanner or what it does leaving a significant gap.
2) It takes up space and also might end up confusing the user. It doesn't have any significant value.
3) It either zooms in on something random or cuts of one part of the page. The user has to to scroll in order to view all the information. At one time some part of the page is cut. 

### Show us how you would improve it
1) Put instructions above the scanner so as to inform the users.
2) Eradicate either the search bar or the "+" sign so as to save space and make it minimalist.
3) The desktop site should be out-scaled in accordance with the grid system.

### How would you measure your designs effectiveness?
There are 3 methods I would suggest:-
1) A/B system testing:It would allow us to construct hypothesis and tell us what certain elements impact the user experience.
2) Multivariate Testing: It allows us to compare a more variables and would give the knowledge as to how they would interact with each other. It will help in measuring the effectiveness of design combinations.
3)  Card Sorting:  It will help to prioritize content and features in the user interface. It will also help in the navigation structure which will lead to data informed decisions.

**Comment by topotropic** [comment]
Thanks for the feedback!

If you find the time, could you open an issue on the [Firefox preview repository](github.com/mozilla-mobile/fenix/issues) for the following (looks like a bug): 

> In some websites when you switch on the desktop site the page doesn't fit on the screen of the mobile.

**Comment by adi-1999** [comment]
Hey @topotropic ,
As you instructed , I have opened up an issue in the Firefox preview repository. 
Here is the link : [#9694](https://www.github.com/mozilla-mobile/fenix/issues/9694)
Thank you!
