### ISSUE TITLE
Pull to Refresh Web Page

### ISSUE THREAD

**Issue by areeshatariq** [mozilla-mobile/outreachy-UX-2020#34]
### What is the problem you are trying to solve?
[#3262](https://github.com/mozilla-mobile/fenix/issues/3262) Pull to Refresh Web Page
### Why is it a problem?
Currently, the refresh icon is located in the menu bar which can be seen when a user clicks the vertical ellipses. Pull to refresh gesture lets a user retrieve new data simply by using touch. Since this gesture has become very common and natural, a user might try refreshing by pulling down the page before finding and clicking the refresh icon. Therefore, to enhance the user-experience, pull to refresh gesture should be implemented.
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77212660-cb7cb400-6b29-11ea-829c-8822897f229c.jpeg" width="50%" height="50%"></p>

### How would you solve the problem? What is your design proposal?

A reload icon will appear when the page is pulled down.

**Icon for Dark Fenix Theme:**
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77213281-1b5c7a80-6b2c-11ea-9bd4-b1e6940daf48.png" width="50%" height="50%"></p>

**Animation:**

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/24654457/77213386-75f5d680-6b2c-11ea-86c4-08fcb049283d.gif)

### How would you measure your designs effectiveness?
**A/B Testing:** By comparing both features of the application (gesture and icon) against each other to determine which one performs better. The above design would be effective if pull gesture performs better. User reviews will also help in working iteratively to improve the design.

**Comment by topotropic** [comment]
Good one! This is coming to Firefox Preview https://github.com/mozilla-mobile/fenix/issues/3262
