### ISSUE TITLE
Import/Export bookmarks to a local file system - Rupali

### ISSUE THREAD

**Issue by Rupali2412** [mozilla-mobile/outreachy-UX-2020#35]
### What is the problem you are trying to solve?
#417 Import/Export bookmarks to a local filesystem

### Why is it a problem?
As a user, it would be inconvenient when the user wants to
- Use firefox preview without signing or logging in
- Switch browser to firefox preview
- Import browsing history data from a device into registered Mozilla account
as the user may want to save data of browsing history/bookmarks.
   
### How would you solve the problem? What is your design proposal?
- Bookmarked pages can be exported in HTML format files in the local file system.
- Also, HTML files can be imported from other browsers and system.
**User flow for importing bookmarks:**
Menu>>bookmarks>>settings>>import bookmarks>>select platform(from where to import)

![Import Bookmarks Gif](https://user-images.githubusercontent.com/60149380/77230875-8013e580-6bbd-11ea-8db3-3f245df15277.gif)

**User flow for exporting bookmarks** :
Menu>>bookmarks>>settings>>export bookmarks

### How would you measure your design's effectiveness?
We can perform usability testing by giving the user a task (import bookmarks) and observing them how whether the user can perform the task smoothly or facing any complication.

**Comment by topotropic** [comment]
Thanks, nice visualization!
