### ISSUE TITLE
Review Firefox Preview  App - Nhi

### ISSUE THREAD

**Issue by hoainhiyiyi** [mozilla-mobile/outreachy-UX-2020#36]
### Name the three biggest issues
1. open tabs show only the title of the page
2. bottom address bar does not hide automatically
3. the open new tab button is not on the navigation bar when viewing a web page

### Explain why it’s an issue 
1. The way Firefox Preview displays opened multiple tabs looks a little bit unappealing since it only shows the title of the page. If I want to find an already open tab, just looking at the page title, it will be difficult for me to know which one is the correct tab. Sometimes, these open tabs lose their content and go back to a blank page.

![image](https://user-images.githubusercontent.com/48849770/77238510-99596980-6b9e-11ea-96df-54a04831b9b7.png)

2. Many people like the design of the bottom navigation bar because it helps users to reach and interact easily with their thumb and without moving fingers all the way to the top when holding the phone. However, I notice that the address bar appears at the bottom all the time which causes distraction when users are trying to read the content of the website.  For example, if a website has a long address with many numbers and symbols, it can make users feel uneasy to read the other content.

![image](https://user-images.githubusercontent.com/48849770/77238538-d02f7f80-6b9e-11ea-87d3-7622a71abc7b.png)

3. It would be better to have an open new tab sign “+” at the main navigation bar whenever users want to switch to another website. In the Firefox Preview app, when I want to open a new tab, it takes me a few seconds to click on the button of tabs number, then continue to click on the “+” 

![image](https://user-images.githubusercontent.com/48849770/77238556-08cf5900-6b9f-11ea-88c2-5631f1694869.png)

![image](https://user-images.githubusercontent.com/48849770/77238559-0e2ca380-6b9f-11ea-8c0a-95d0de407e0f.png)

### Show us how you would improve it

1. It would be better if the open tabs can show the screenshot of a web page’s content.
2. The address bar should be disappeared automatically when scrolling and coming back when we touch slightly at the bottom or scrolling to the top.
3. Open new tab button “+” can be put near the address bar and tab’s numbers sign, so users can save time from switching to other things to do this process. 

### How would you measure the effectiveness of your designs?

I can measure the effectiveness by reviewing the comments from users. These are the essential feedbacks that users actually experience when they are using the app. From them, I can know which aspects need to be improved and fixed in order to serve users’ needs. The other way is to follow the trends of UI or UX designs that are familiar to users and attract them easily. For example, the bottom address bar is a highlight of Firefox Preview app which can get new users’ attention quickly, but if we can make it auto disappear while using the app, users will feel convenient and willing to try something new that more interested than the style of traditional web browsers.

**Comment by topotropic** [comment]
Thanks for the feedback!
