### ISSUE TITLE
Send tab feature #246-Riya

### ISSUE THREAD

**Issue by riyasoganii** [mozilla-mobile/outreachy-UX-2020#37]
### What is the problem you are trying to solve?
Send tab feature #246
https://github.com/mozilla-mobile/fenix/issues/246

Sending tabs to other devices integrated with Firefox Accounts #5400
https://github.com/mozilla-mobile/fenix/issues/5400
### Why is it a problem?
As a user, I would like the option to send my tabs to other synced devices and other social media for easier and quicker access. This would greatly increase conveniency, as the only other way to share tabs currently is to copy and paste the link.
### How would you solve the problem? What is your design proposal?
Currently, the gesture to delete tabs is to swipe either left or right, or press the 'x' button on the tab. We can change these gestures to: swipe left for deletion, and swipe right for sharing. we can also add a 'share' icon next to the 'x' button on the tab, for more of a visual access.
![Tabs (17)](https://user-images.githubusercontent.com/59031971/77243329-cfdec500-6c2e-11ea-982d-67c3e70aa64e.png)

On sharing, the following screen would pop up, directing the user to the various means of sharing.

![Tabs (18)](https://user-images.githubusercontent.com/59031971/77243336-e258fe80-6c2e-11ea-8a34-52e73381be3a.png)

### How would you measure your designs effectiveness?
We could introduce the user to these gestures on installation of the app, so as to not go overlooked. We can then compare the number of users who use the share button as compared to the share gesture (right swipe), and modify our design accordingly.

**Comment by topotropic** [comment]
Thanks for the design proposal.

If you have time, I'd be curious to learn more about how you would do that:

> introduce the user to these gestures on installation of the app

**Comment by riyasoganii** [comment]
@topotropic On installing an update with new features, we could introduce a 'Whats new?' one-time popup for the user. This popup could contain easy to understand details of new features along with descriptive images/animations. I feel this feature is necessary for the user to prevent new updates and gestures from going overlooked. The way to close this popup could be a 'Got it!' button at the bottom of the popup. This prompts the user to read the popup rather than to instinctively press a 'x' button had it been located at the top of the popup.
![Tabs (44)](https://user-images.githubusercontent.com/59031971/78333232-12958b00-75a7-11ea-8910-2f512bb0947d.png)
