### ISSUE TITLE
Pull down to Sync-Riya

### ISSUE THREAD

**Issue by riyasoganii** [mozilla-mobile/outreachy-UX-2020#38]
### What is the problem you are trying to solve?
Pull-down bookmarks/history lists to trigger sync #2165
https://github.com/mozilla-mobile/fenix/issues/2165

Sync collections #4424
https://github.com/mozilla-mobile/fenix/issues/4424

[Meta] Sync open tabs #5762
https://github.com/mozilla-mobile/fenix/issues/5762
### Why is it a problem?
As a user, I would like a universal gesture to trigger sync on all forms of data (bookmarks, history, tabs, collections)
## How would you solve the problem? What is your design proposal?
As mentioned in my design solution on  the issue, 
Review Firefox Preview-Riya #10
https://github.com/mozilla-mobile/outreachy-UX-2020/issues/10
I have mentioned that tabs and collections can be displayed as two separate menus which can be scrolled through individually. Using this new design I have incorporated a gesture 'Pull down to sync'. These menus can be pulled down individually to sync tabs/collections respectively on all firefox devices. When the menu is slightly pulled down, the sync logo is in a dark grey, as shown, and partially hidden.

![Tabs (19)](https://user-images.githubusercontent.com/59031971/77243988-40d5ab00-6c36-11ea-97b8-032ab03f0ff7.png)

As the menu is pulled down more, more of the sync logo is shown. When the menu is fully pulled down, the sync button turns white and all tabs/ collections are synced.
![Tabs (20)](https://user-images.githubusercontent.com/59031971/77244000-5a76f280-6c36-11ea-90c6-bb2a38b582c3.png)

The menu button (3 vertical dots) next to tabs/ collections can be used to access synced tabs/collections.
![Tabs (21)](https://user-images.githubusercontent.com/59031971/77244009-81352900-6c36-11ea-8d37-4b24304cd7a5.png)

Similarly, this same gesture can be used on the bookmarks and history menus to sync those as well.
![Tabs (22)](https://user-images.githubusercontent.com/59031971/77244017-914d0880-6c36-11ea-89d1-c08d68c63c68.png)
![Tabs (23)](https://user-images.githubusercontent.com/59031971/77244018-927e3580-6c36-11ea-9c6f-c18fa27f4bea.png)

EDIT:
For further information, I have made this design quite similar to my design solution for 'Pull down to refresh' in order to ensure consistency throughout designs, which is an integral part of UI/UX.
https://github.com/mozilla-mobile/outreachy-UX-2020/issues/14

### How would you measure your designs effectiveness?
Apart from a user UI survey, we should also introduce the users to this gesture as it is something new and hence not very instinctive. It can be optionally turned off in the settings. Once the users get used to this gesture, we can track the amount of usage of the same, and determine if we need to continue with the same gesture of perhaps introduce a new one.

**Comment by topotropic** [comment]
Thanks for the proposal. 

Two follow up questions if you have time:

- Do you think we need to differentiate in the UI whether a tab is synced or not? 
- What do users see who are not logged in to their Firefox account and can't sync?

**Comment by riyasoganii** [comment]
@topotropic This sync feature would be disabled by default to a user who is not logged into their Firefox account. Then, once a user is logs in, we can introduce a popup saying 'You can now...' which informs them of the synced tabs, bookmarks, and history. This is a nice way of informing the user of the gestures and feature as well.
And yes, users should be aware of the which tabs are synced- as they might not want to change tabs on their other devices. Thanks for bringing this to my attention! I have a proposed idea:
We can include a very translucent sync logo on the bottom left of tabs which are synced. On tapping this logo, the user can view which device this tab is synced to, like so
![Tabs (46)](https://user-images.githubusercontent.com/59031971/78419718-3370e580-7666-11ea-9385-37ad74e49f98.png)
![Tabs (45)](https://user-images.githubusercontent.com/59031971/78419720-353aa900-7666-11ea-92b0-9c306d5b8327.png)
