### ISSUE TITLE
Search in setting

### ISSUE THREAD

**Issue by Gunkev** [mozilla-mobile/outreachy-UX-2020#39]
### What is the problem you are trying to solve?
Search parameters elements
### Why is it a problem?
In the firefox preview app I noticed that there was no way to find an element in the setting without scrolling all the way downward. Hence when A user may lost some time scrolling up and down.
### How would you solve the problem? What is your design proposal?
In the firefox preview app I will rather add a search widget which will permit users to input what they are looking for and choice between results rather than scrolling all the way and wasting time.
Here is an interface I propose
### How would you measure your designs effectiveness?
All my work will be measured based first of all on user's need secondly I will work with my team hands in hands in order to get more accuracy and improvement proposals.

![search parameters](https://user-images.githubusercontent.com/36812576/77247917-d91f6000-6c35-11ea-955a-f071e9757691.png)

**Comment by topotropic** [comment]
> on user's need secondly I will work with my team hands in hands

I really like that approach :-)
