### ISSUE TITLE
FxA auto Sign-in

### ISSUE THREAD

**Issue by Gunkev** [mozilla-mobile/outreachy-UX-2020#40]
### What is the problem you are trying to solve?
FxA auto Sign-in
### Why is it a problem?
Some user may want to have the possibility to auto sing in in other Firefox products, such that they may switch easily to other fennec product found on their device without necessarily signing in again hence saving time. It may also happens that an a Firefox app which they are using crashes and if this happens user will like to continue their task in another Firefox related app on their device without starting over again.   
### How would you solve the problem? What is your design proposal?
A simple way is the offer user the possibility to synchronize and automatically sign in in other firefiox account found on their device
### How would you measure your designs effectiveness?
I will still on working directly with users from different domains and getting feedbacks 

![FxA auto sign](https://user-images.githubusercontent.com/36812576/77248429-8f387900-6c39-11ea-88ec-a06f71ec461a.png)

**Comment by topotropic** [comment]
Thanks for the proposal – looks worth investigating for sure!
