### ISSUE TITLE
Sync open tabs

### ISSUE THREAD

**Issue by Gunkev** [mozilla-mobile/outreachy-UX-2020#41]
### What is the problem you are trying to solve?
Synchronization of open tabs
### Why is it a problem?
Some user may like to switch from one device to another due to portability or domestic problems like low battery or even because of a phone crash. If any of this happens a user as me will like to continue my work directly from where the incident happened on another device.
### How would you solve the problem? What is your design proposal?
An idea is to synchronize all open tabs to other devices such that if an incident happens, I will switch to another device and continue my work while the other device I will using previously is been taken in charge. First of all when sign-in in I will automatically sign-in in other Firefox accounts. When finally signed-in I will toggle the "synchronize with open tabs on other devices" so that each tab I open equally opens in other devices.
### How would you measure your designs effectiveness?
I will measure ;y design effectiveness base on user feedback and from general team point of views.

![sync open tabs](https://user-images.githubusercontent.com/36812576/77248740-0f5fde00-6c3c-11ea-8db5-f1b464c69558.png)

![Screenshot_20200322_095424_org mozilla fenix](https://user-images.githubusercontent.com/36812576/77248759-2d2d4300-6c3c-11ea-94b3-e445bd9f6441.jpg)

![Screenshot from 2020-03-22 09-55-13](https://user-images.githubusercontent.com/36812576/77248774-54841000-6c3c-11ea-80a4-dbaf37b5eb37.png)

**Comment by topotropic** [comment]
Makes a lot of sense.

Do you think it's important to indicate to users that certain tabs are synced from another device?

**Comment by Gunkev** [comment]
Thanks very much @topotropic. I think that point is important too  and Good to indicate since it will permit user to know when did they use a particular device if they are found to be in some unknown condition

**Comment by Gunkev** [comment]
Thanks very much @topotropic. I think the point is important too  and Good to indicate since it will permit user to know when did they use a particular device if they are found to be in some unknown condition
