### ISSUE TITLE
Add Dictionary Feature in Reader Mode

### ISSUE THREAD

**Issue by areeshatariq** [mozilla-mobile/outreachy-UX-2020#42]
### What is the problem you are trying to solve?
Add Dictionary Feature in Reader Mode
### Why is it a problem?
In reader mode, there is no quick way to see the meaning or pronunciation of a word. Currently, a user can search the highlighted text (Firefox Preview Search) but it requires a minimum of 3 taps. Hence, there should be some quick way to look at the dictionary for a particular word while the user is in reader mode. 
### How would you solve the problem? What is your design proposal?
In reader mode, if a user highlights a word, a pop-up would appear at the bottom of the screen showing the pronunciation and meaning of the word (dictionary). The user can click the dictionary which will open up the meaning of the word on a search engine.

**Design**

<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77261920-ea0eb680-6cb3-11ea-911e-dc18bb93103f.jpg" width="50%" height="50%"></p>

### How would you measure your designs effectiveness?

- By testing the feature on some users and getting their feedback. User reviews will help in working iteratively to improve the design. 
- By comparing the feature with the competitors

**Comment by topotropic** [comment]
Interesting idea! I like it. 

Is it on by default – will it show up for every word I select? What's going to happen when I select multiple words? Thanks!

**Comment by areeshatariq** [comment]
@topotropic yes, it will be enabled by default in reader mode. I will show up for every word/phrase that is selected.
