### ISSUE TITLE
Enhancing Mozilla’s private browsing.

### ISSUE THREAD

**Issue by sunidhi-kashyap** [mozilla-mobile/outreachy-UX-2020#43]
Issue #1

The positioning of “**delete history**” button.
Since a good private browser should help you to clear the search history fast, as a local attacker enters the room, the delete button must be “**more reachable**”.

![Group 76](https://user-images.githubusercontent.com/42182441/77302079-c4ff5f80-6d16-11ea-936b-a82d18190425.jpg)

Solution : Even though the button is very prominent, considering the phone is in one hand of the user(say, right), the button should be positioned at the “bottom” for the thumb to reach there fast and conveniently.

Issue #2

During the onboarding, there’s a private window icon at the top. Clicking which toggles the browsing experience but there are no visual cues that you are browsing privately. Do you even need that icon when you haven’t clicked on “Start Browsing”?

![Screenshot_20200323-144021](https://user-images.githubusercontent.com/42182441/77302188-fb3cdf00-6d16-11ea-87a5-a0027e3d9716.png)

To resolve this issue, we could use a "bottom sheet", indication the user. Or we could use some more thinking on its need when the browsing hasn't even started.

**Comment by topotropic** [comment]
Thanks for the feedback! 

I like your second observation a lot. Can you explain or visualize what you mean here:

> To resolve this issue, we could use a "bottom sheet", indication the user. Or we could use some more thinking on its need when the browsing hasn't even started.

**Comment by sunidhi-kashyap** [comment]
> Thanks for the feedback!
> 
> I like your second observation a lot. Can you explain or visualize what you mean here:
> 
> > To resolve this issue, we could use a "bottom sheet", indication the user. Or we could use some more thinking on its need when the browsing hasn't even started.

Thanks for appreciating!

What I meant was, we can use a bottom sheet to indicate the user that private browsing has begun.
![Group 97](https://user-images.githubusercontent.com/42182441/78399700-05ae8100-7613-11ea-94c6-adbdfa9a7b8b.png)

This is the design that I visualised.

"Or we could use some more thinking on its need when the browsing hasn't even started."

By this I meant, maybe we don't need the private browsing icon at the time of on-boarding.Since the user hasn't even **started browsing** yet, the private browsing icon feels unessential.
