### ISSUE TITLE
Easter George- Firefox Preview Review

### ISSUE THREAD

**Issue by EasterGeorge** [mozilla-mobile/outreachy-UX-2020#44]
Issue 1:
Placement of the Omnibox at the bottom 
As someone who has used the Mozilla Firefox browser first on PCs, I expected to see the Omnibox at the top of the page. It took me longer to find it at the bottom. Then when one starts typing  it relocates to the top then on enter it goes back to the bottom
Problem: Inconsistency with design. Tab placed at the bottom
Solution: Place the tab at the top

Issue 2:
Omnibox by default is at the bottom
Browsers such as Chrome and Firefox place their Omnibox at the top of the screen and some at the center. Firefox Preview’s is at the bottom by default and can be altered to be placed at the top always.

As an experienced user, I fiddled with the settings and altered it.
Solution:
Studies to be conducted to find where users prefer the Omnibox to be at.
Also find out if many novice users will alter the placement or perceive the placement to be final and unalterable.

Issue 3:
The search icon next to the shortcuts selection is ambiguous.
 It took me a couple of days to discover that it meant showing and hiding the search options’ settings.

To mean that we are changing the search settings by ![hiding](https://github.com/EasterGeorge/images/blob/master/Screenshot_20200312_170044_org.mozilla.fenix.jpg?thumbnail) and ![showing ](https://github.com/EasterGeorge/images/blob/master/Screenshot_20200312_165944_org.mozilla.fenix.jpg) search options.
 
When shown one can change on what site they want to search content on. By default it is Google. I found the feature very useful and convenient in my personal use.

Solution:
The search settings could be changed in a different way,for example, if the ‘G’ with the google colors was designed to be clickable and hence such settings changed like that.

Use of a clearer word and icon combo. For example, search settings with the search as an icon and settings in place of shortcuts.

**Comment by topotropic** [comment]
Thanks for your feedback!
