### ISSUE TITLE
Feature Request- Hover over Private tab links-Advika Singh

### ISSUE THREAD

**Issue by adi-1999** [mozilla-mobile/outreachy-UX-2020#45]
Scenario:- Suppose our user is in a public space, and wants to open private tabs . The user definitely don't want people to see the links that have been opened. Since one can see that all the links are clear as day , it will put the user in an awkward position to open them in public. 

Feature:- The links initially show the websites logo only. When you hover over them the links expand allowing the user to see the full link.
It will allow the user to keep their privacy while making them comfortable opening them in public areas.  It will definitely ease the usability of the app.

**Comment by topotropic** [comment]
This is an interesting observation. I'm curious to learn more about how you would reveal a page title, URL in private mode. Thanks!
