### ISSUE TITLE
Design issue/feature request-Closing of private tabs-Advika Singh 

### ISSUE THREAD

**Issue by adi-1999** [mozilla-mobile/outreachy-UX-2020#46]
If the user exits the app while some private tabs are open, the user receives a notification to close the private tabs. However, if you click that notification , all the private tabs would close , which can be of inconvenience . What if the user doesn't want to close all tabs?

**Feature Request/Proposal**- The user can expand the notification to either close all tabs or get a list of tabs open and can close them individually. 
This  will save the users time and effort of recovering old closed tabs and gives the user freedom to close what user pleases. 

Some of the design explorations could be these :- 

1) We could have a private basket , whenever the user closes the app , all the open tabs go the basket . Whenever the user opens the app again , the homepage of the private mode would be empty and the user could access their previous open tabs through the basket . This basket would have a privacy lock on it. The user will receive a notification which will say to "put all tabs in the basket". If certain tabs are not accessed after a limited small amount of time (can be set by the user) , then the tabs would close automatically.  

 2) We can allow the user to choose the tabs that they want to be remained open (in the private mode, on the homepage) and the rest of the tabs automatically close when the user opens the app the next time. A private basket that would allow people to put the tabs that they want to be remained open. Following this we can go 2 ways, whenever the user opens up the app again, all the tabs can be closed (through the basket the user can access the tabs they wanted to be remained open) or only the basket tabs would show up with the rest closed. This basket would have a privacy lock on it. The user will receive a notification which will say to "put tabs in the basket". If certain tabs are not accessed after a limited small amount of time(can be set by the user) , then the tabs would close automatically.  
 
** Please see that the above are just some of the solutions and proposals given. The solution may vary from person to person. However, the best one under the circumstances is given and would appreciate new ideas. :)

**Comment by topotropic** [comment]
Thanks! This is a good observation.

I'd be curious to see some more design explorations. I'm wondering if your proposal is too demanding – especially when people have a lot of private tabs – when people just quickly want to close private tabs.

**Comment by adi-1999** [comment]
Hi @topotropic !
Some of the design explorations could be these :- 

1) We could have a private basket , whenever the user closes the app , all the open tabs go the basket . Whenever the user opens the app again , the homepage of the private mode would be empty and the user could access their previous open tabs through the basket . This basket would have a privacy lock on it. The user will receive a notification which will say to "put all tabs in the basket". If certain tabs are not accessed after a limited small amount of time (can be set by the user) , then the tabs would close automatically.  

 2) We can allow the user to choose the tabs that they want to be remained open (in the private mode, on the homepage) and the rest of the tabs automatically close when the user opens the app the next time. A private basket that would allow people to put the tabs that they want to be remained open. Following this we can go 2 ways, whenever the user opens up the app again, all the tabs can be closed (through the basket the user can access the tabs they wanted to be remained open) or only the basket tabs would show up with the rest closed. This basket would have a privacy lock on it. The user will receive a notification which will say to "put tabs in the basket". If certain tabs are not accessed after a limited small amount of time(can be set by the user) , then the tabs would close automatically.  

These have also been updated in the document.
