### ISSUE TITLE
Learn about other Fx Products #4634-Riya

### ISSUE THREAD

**Issue by riyasoganii** [mozilla-mobile/outreachy-UX-2020#47]
### What is the problem you are trying to solve?
Learn about other Fx Products #4634
https://github.com/mozilla-mobile/fenix/issues/4634
### Why is it a problem?
As a user, on trying out this browser for the first time, I'd like to make an informed decision about whether or not I should make it my default browser. With so many other competitors in the market, it is essential for the users to know the uniqueness of the service they are being provided, its functionality, and hence why they should prefer it over all other options.
### How would you solve the problem? What is your design proposal?
I have come up with two proposed design solutions to the same. On clicking a specific link, the users should be directed towards the site: https://www.mozilla.org/en-US/firefox/ (In their specifc language), where they can obtain further information about the product.
This link can either be located in the top right of the home screen for a very evident yet subtle approach, like so:
![Tabs (24)](https://user-images.githubusercontent.com/59031971/77511390-01f26000-6e97-11ea-9829-26faf9bdec0c.png)

Otherwise, the link can be accessed by pressing the firefox logo (pointed to) for a more intuitive gesture:
![Tabs (25)](https://user-images.githubusercontent.com/59031971/77511447-19c9e400-6e97-11ea-9b78-938efe363ec1.png)

### How would you measure your designs effectiveness?
I would first roll out the logo clicking design and record the number of clicks on that. I would then roll out the design with the link on the top right, and compare the number of clicks with that of the previous approach. We would then be able to tell which design is more effective and act accordingly.

**Comment by Gunkev** [comment]
Good approach. I think you need to polish your "more about us" make it look more good and provide a way which will incite a user to want to click on it.

**Comment by topotropic** [comment]
Thanks for the proposal. 

That's a great design challenge:

> I'd like to make an informed decision about whether or not I should make it my default browser

Can you think of other ways to show users the value they get with Firefox Preview and tell them about other products Mozilla is offering?

**Comment by riyasoganii** [comment]
@topotropic Although we can add this 'More about us' link that would direct the user to the Mozilla website, there is no guarantee that they would click on it. To make the process of receiving this information more certain, we can introduce an interactive approach.

When a user installs the app, we can ask them whether they are a new Mozilla user or not. If they are not, then we ask them to sign in, but if they are, we ask them to create a mozilla account (the user can choose to do this later) and we also activate a series of popups which can be used to introduce a new user to the uniqueness of the features of mozilla.

By this I mean, for example, when the shield icon is activated in the address bar for the first time, we can introduce a small dialogue box which conveys that it is a feature used for content blocking- as this might not be intuitively understood by a new Mozilla user. Similarly, we can introduce other dialogue boxes for the first time a user interacts with any Mozilla-specific feature. 

This way, we are fulfilling the responsibility of keeping the user informed.
