### ISSUE TITLE
Separate Private Mode search engine - Rupali

### ISSUE THREAD

**Issue by Rupali2412** [mozilla-mobile/outreachy-UX-2020#48]
### What is the problem you are trying to solve?
User may want to change the default search provider.
https://github.com/mozilla-mobile/fenix/issues/1076

### Why is it a problem?
The user might not want to use Google as a default search engine as they can be more careful about the tracking of their IP address and other tracking mechanisms like browser fingerprinting. 

### How would you solve the problem? What is your design proposal?
1. When the first time a user changes the search engine in incognito mode, a dialogue box asking if the user wants to make the default search engine.
2. The description on the incognito home page can also include a suggestion about trackers in search engines.
![Group 42](https://user-images.githubusercontent.com/60149380/78278142-3919de80-7533-11ea-9c18-86a1f81a072a.png)

### How would you measure your design's effectiveness?
An effective way is to check the analytics of user actually changing the default search engine. 
Also tracking the number of users leaving the incognito mode after pop-up of the dialogue box.

**Comment by topotropic** [comment]
Thanks for the proposal. 

What happens if a user ignores the dialogue box – are there other ways to tell users about this feature?

**Comment by Rupali2412** [comment]
Thanks for the feedback @topotropic . Yes, a description on the homepage of incognito mode is there. 
![pri](https://user-images.githubusercontent.com/60149380/78395774-bfa1ef00-760b-11ea-9e5d-736cf40ed779.png)
Also, we can give user an option to change search engines for both modes differently.
