### ISSUE TITLE
Issue related to the "top sites" section of the homepage

### ISSUE THREAD

**Issue by sunidhi-kashyap** [mozilla-mobile/outreachy-UX-2020#49]
issue #1 
**The interaction to pin tabs on the home-page is not easily discoverable.**
I did a little survey to verify this issue.
I asked 3 people, all 3 from different work backgrounds, to add their favourite site to top sites. And here’s the results I got.
![Group 85 (1)](https://user-images.githubusercontent.com/42182441/77612974-87394b80-6f4f-11ea-9b72-02e946acb3b9.jpg)

**Design proposal;**

                    existing design                                re-designed

![Group 86 (1)](https://user-images.githubusercontent.com/42182441/77613040-bbad0780-6f4f-11ea-8612-6195303708bc.jpg)

This is one possible solution to the problem.

**Effectiveness of the design?**
Having the option show when the user selects the tab, is very intuitive to the user.

Another design change could be, if the user can simply **"drag and drop"** to the top sites.

issue #2 
**User can add a page to “top sites” even if it’s already there.**

This doesn’t seem to be an issue, but it actually is. A user might not remember if the site he just visited was already there. So, adding it again, by mistake, would be useless. Also, a waste of space. Moreover, the user will have to remove those extra tabs, once the space starts to look jammed.
![Group 87](https://user-images.githubusercontent.com/42182441/77613374-8ce36100-6f50-11ea-877e-b2a662936ec8.jpg)

To avoid this, displaying a simple pop-up message, instead of adding the new tab, should do the job.
![Group 76 (2)](https://user-images.githubusercontent.com/42182441/77613417-a2588b00-6f50-11ea-98fb-115030dd561a.jpg)

**Comment by Gunkev** [comment]
Good idea. But how will user manage their top website like remove some or all in home page ?

**Comment by sunidhi-kashyap** [comment]
> Good idea. But how will user manage their top website like remove some or all in home page ?

I may have not been clear i guess, but the rest of the interaction remains the same. My only point was, provide user an interface which helps him use the feature effortlessly and the interaction is very intuitive. Since, all of the users don't spend much time discovering new features of an app, but just go with what is most reachable/discoverable to them.

**Comment by topotropic** [comment]
Thanks for the feedback. I very much liked your quick hallway test you documented here. I agree that the feature has some discoverability issues and your approach is interesting.

**Comment by sunidhi-kashyap** [comment]
Thanks for the appreciation!
