### ISSUE TITLE
Review Firefox Preview - Sabiha

### ISSUE THREAD

**Issue by Sabihashaik** [mozilla-mobile/outreachy-UX-2020#50]
### Name the three biggest issues
1.  Crowded Home Screen
2.  Positioning of Bookmarks Feature
3.  Positioning of Scan Tab Feature 

### Explain why it’s an issue 
Before tackling each issue in detail, I will be presenting some sample user personas to explain where a particular type of user may face difficulty. 

_David Smith_ - A 40 year old retired worker who is interested to do a quick google search on some garden tools for his home. 

_Sarah Myers_ - A 20 year old college student pursuing a undergraduate in humanities who browses articles and reading during her daily bus commute. 

_James Brown_ - A 25 year old software developer living in an area with poor network connectivity (with proper connectivity only few hours a day) who enjoys learning about new technologies and improving his skill set online. 
 
 -------
_Screenshots and sketchnotes explaining the below are uploaded [here](https://www.docdroid.net/40ZhrOm/firefox-preview.pdf)_ 

**Issue 1 - Crowded Home Screen**
On first glance, the Home Screen has multiple dominating factors that digress the attention of the user.  The presence of "Collections" section even when no collections have been created yet as well as the top bar with pre-bookmarked pages (Top Articles, Wikipedia, etc.) all direct the attention of the user. 

Considering a senior aged user such as David Smith, he would need help to figure out how to do a simple search. Would he have to click the 3 vertical dots next to Open Tabs? Start a new collection or press one of the icons from the pre-bookmarked pages?  These are all questions he would have to decide on. 

The positioning of the search bar/open tab feature is not very intuitive for a senior aged user such as David Smith. 

**Issue 2- Positioning of Bookmarks**
For a user who is on the go and quickly reads and wants to save articles that they read such as Sarah Myers, the feature to add a bookmark to a page is not very intuitive. 

The Star Icon does not clearly demonstrate that it would create a bookmark. Only when the user clicks it a text "Bookmark added"  helped understand that a bookmark has been created. 

Moreover, when Sarah Myers clicks the 3 vertical dots menu when active on a page, the menu has a lot of options that hint to similar functionalities such as: 

1. Add to top sites
2. Add to Home screen 
After a bookmark is added, viewing the bookmarks requires multiple clicks and cannot be accessed directly from the home page of the app. Users would be confused about the difference between Collections and Bookmarks as they both hint to the same functionality as per the name. 

**Issue 3- Positioning of Scan Tab Feature**
The Scan Tab feature is very unique and is a quick way for users to open tabs from a QR code. James Brown has a lot of tech events in his community which share QR codes on a poster for easy links to attendees. 
However, with the current placement of the Scan Tab feature, James has to perform multiple clicks to access the scan tab feature. That is, clicking on the search bar and then clicking on the "Scan" option. Due to his unstable network connectivity, this would often affect his chances of opening a web page quickly and successfully. 
 
### Show us how you would improve it
**Issue 1 - Crowded Home Screen** 

- Hide the description under Collections section by default. Instead add an arrow next to the Collections side bar to view the collections that have been created. 
- Add an Open Tab (+) feature next to the 3 vertical dots menu. 

**Issue 2 - Positioning of Bookmarks Feature** 

-  Change the "Star" icon to a "Page Mark" Icon to better represent bookmark feature. 
-  Club the "Add to top sites" & "Add to Home screen" together under an expandable "Add to" with an arrow that expands to show options "Top Sites" and "Home Screen". The bookmark feature can also be moved under this section. 
- View Bookmark function should be moved next to the Collections tab on front page for ease of access. 

**Issue 3- Positioning of Scan Tab Feature**
- Should be moved to the main page preferably near the + icon in the search bar. 

### How would you measure your designs effectiveness?
The most accurate way to measure the effectiveness would be to test it among the target personas that created. Multiple designs can be created and A/B testing can be performed.

**Comment by topotropic** [comment]
Thanks for your feedback!
I really liked your annotated scribble, the user profiles and you have some solid feedback.

**Comment by Sabihashaik** [comment]
Thank you! 😄
