### ISSUE TITLE
Past Work- Design Portfolio - Sabiha 

### ISSUE THREAD

**Issue by Sabihashaik** [mozilla-mobile/outreachy-UX-2020#51]
- A portfolio of my past projects can be found at [Behance]( https://www.behance.net/sabihaabc162d5)

- Designed [promotional posters](https://1millionwomentotech.com/summerofcode1/sharing-is-caring/) for 1 million women to tech initiative.

- Github with code for the applications can be found [here](https://github.com/Sabihashaik/)

------
### Food 4 Us

![header](https://user-images.githubusercontent.com/21033484/77624577-75f63c00-6f5b-11ea-8ddc-bafde74ed5b1.png)

A project that I want to highlight which I worked on as a submission for the Microsoft Big Idea Challenge 2018. 

Food For Us is a mobile app solution which provides a platform for people and businesses who wish to donate food connect with those who wish to receive it. In just 3 easy steps, Take a photo, Tag It and upload! Those who require donations can accept and collect the donation. Whereas, those donating can benefit through a number of rewards such as Vouchers and Points earned for every donation. These transactions can be made anytime, anywhere.

**My thought process**

- _User Journey_
I mapped out the users’ steps to see how I could simplify their journey to help them reach their most important goals with the product.

- _Value Proposition and Business Model_
Based on User Reviews and Interviews a value proposition model taking into account user pains, gains and Jobs was created. Interacting with potential users and target market helped shape and make decisions to which features would be more preferred by certain target groups.

- Sketches (Screen Set 1) 
I usually start the design process with sketches of the layout for the app. This is the way I iterate through many design options quickly.
The main purpose was to understand the layout before making the design on Figma. To create the designs I referred to other applications which have a gamified approach to solve a social issue.
I created a set of screen sketches for the Organization end as well. This included forms that a NGO would have to fill in to be registered on the app as well as screens to alow them to post Ads on the app.

- Personas
Based on the interviews / surveys I set up sample personas and referred to them throughout the entire product development process.
The softwares that I usually use are Figma and Adobe XD for UI design. 

> **Robert Jennings**
> Robert Jennings has been the owner of The Maryland, a 100 seater restaurant for the last 17 years. He is a family man and the restaurant has been in his family for three generations. He is a socially conscientious man and devotes a significant part of his evenings volunteering at the local pantry. He recently found that his restaurant wastes 5% of all food prepared and he is concerned. He wants an easy way to donate food since he runs on a tight schedule.

- User Stories
At the discovery phase of my project, I conducted user interviews and created sample user stories in order to get a better understanding of the problem.
- UI Design
Once I had all the sketches, I started designing the final screens in Figma. The style I followed was mainly to be user friendly and I try tried to follow the Material Design Approaches. It is mainly designed for the Android platform.
 
 ----

**Comment by topotropic** [comment]
Thanks for sharing!
