### ISSUE TITLE
Past Work- Design Portfolio - Rupali

### ISSUE THREAD

**Issue by Rupali2412** [mozilla-mobile/outreachy-UX-2020#52]
- My interaction and design portfolio can be found at https://www.behance.net/rupalirimi24
- My UX portfolio website can be found at - https://rupali2412.github.io/Rupaliportfolio/index.html

In my quest to be an interdisciplinary designer, I’ve tried to take on various projects, internships as well as contributions to open source organisations. Each project had a unique set of requirement. Some of them are the following:

**Highway Delight (UI Project):** I redesigned the UI of the app consisting of a lengthy form filling process to be more engaging and interesting using concept os gamification.  
**Cusp/Dexpert (UX Project):** I created an intuitive design from scratch to the development of the application. I worked on a platform to connect individual designers to employers in which I learned about Agile Project Management. 
**Thomso’19 App (UX Project):** In this project, I followed a process of user research and worked on how it can be used to enhance the overall experience of college fest attendee.
**24 icon pack (Graphic design):** This icon pack includes the component of product placement.
**A complete personal Assistant (Case study)**: This is my first UX project. I followed an extensive process from user research to working on a double-diamond method to find the defining features of the product.

**Comment by topotropic** [comment]
Thanks for sharing!
