### ISSUE TITLE
 Voice input for Search #1216 

### ISSUE THREAD

**Issue by Vaishnavi-Reddy-Kancharla** [mozilla-mobile/outreachy-UX-2020#53]
**What is the problem you are trying to solve?**
Voice input for search issue.
**Why is it a problem?**
Not having a voice input for search in a browser is a problem as voice input for search is becoming the common search method these days. Over the last two decades, humans have managed to smoothen the transition from text search to voice search as it is convenient and immediate. Typing something on a browser to search during multitasking and especially when your hands are occupied in some tasks such as cooking, cleaning, etc is really difficult and not having voice input for search would make it even harder. As it is also said the android microphone icon on their keyboard and voice search option can be used instead is a problem as every mobile phone wouldn't have such an option and it is very common for a user to expect it in a search bar.
**How would you solve the problem? What is your design proposal?**
I would recommend using a voice search option in the search bar to the right and at the end of the search bar as most of the users expect it to be present. Having a little microphone icon would make it obvious for a user that it is for voice search. 

![91354631_2325460691086314_1369146509227982848_n](https://user-images.githubusercontent.com/60965381/77769489-eee3b980-7069-11ea-90fe-44c0d3d97f0e.jpg)

 **How would you measure the effectiveness of your designs?**
I measured my design effectiveness by 2 ways
1. When i open a browser app I tend to see search bar first and i also notice microphone at the end of search bar which makes me go for voice input
2. Survey: I did a survey regarding my design giving participants two options which is (1)having microphone at the end in the search bar and (2)having microphone anywhere in the browser and 46 out of 50 participants preferred microphone at the end of the search rather than having it anywhere else.

**Comment by topotropic** [comment]
Thanks for your proposal! I really liked how you embedded your design in an everyday scenario

> during multitasking and especially when your hands are occupied in some tasks such as cooking, cleaning, etc

Also impressive that you verified your design proposal already!

>     46 out of 50 participants preferred microphone at the end of the search
