### ISSUE TITLE
Download Manager UI #4417- Advika Singh

### ISSUE THREAD

**Issue by adi-1999** [mozilla-mobile/outreachy-UX-2020#55]
### What is the problem you are trying to solve?
Download Manager UI  [#4417](https://github.com/mozilla-mobile/fenix/issues/4417)  
Sub issue - [#349](https://github.com/mozilla-mobile/fenix/issues/349) 

### Why is it a problem?
A user might want to access all the downloaded files or look for a particular downloaded file within the browser. For that,it is important to show the whole history of the users downloads. However, this piece of information should be easily accessible. The user should be able to find this quickly and easily.  

### How would you solve the problem? What is your design proposal?
The following process can help in finding a solution : -
**1) Competitive analysis** - Finding the top most competitors and analyzing their features and finding ways to incorporate the best ones according to the needs of our users and the context of the application.
**2)** Now according to the competitive analysis , a **information architecture** (narrow and deep workflow from Page A to Page B) should be made to find out how can the user finish the task in minimal amount of time.
  Important information like that should not be more than 2 clicks away from the homepage. As I have already said that the user should able to easily access it. 

**Design Proposal**:- To the right of the search bar are the dots that opens up a menu containing settings, bookmarks , history. It would be viable to put a downloads button there , among other options. When clicked on the downloads option, it should open up the downloads by the date along with the location where they have been saved.

**Examples:-**
**1) Chrome**
<img src="https://user-images.githubusercontent.com/58343952/77799747-74cc2880-709b-11ea-937a-1ea99a04e580.jpeg" alt="" width="250">

<img src="https://user-images.githubusercontent.com/58343952/77800214-4f8bea00-709c-11ea-9886-28d7d2bd843a.jpeg" alt="" width="250">

**2) Opera Mini**
<img src="https://user-images.githubusercontent.com/58343952/77800265-6af6f500-709c-11ea-9b84-c3b7a4619b73.jpeg" alt="" width="250">

<img src="https://user-images.githubusercontent.com/58343952/77800280-7518f380-709c-11ea-8218-bb35baa7cdd5.jpeg" alt="" width="250">

### How would you measure your designs effectiveness?

**Unmoderated remote usability testing** :- The user can complete certain tasks ( like,download an image and open it, See what you have downloaded on a specific date. See when did you download a specific file) that revolve around the specific feature. But the user gets to do this in an environment they are comfortable with.
This will help us observe user behavior patterns.

**Contextual inquiry through reviews** :- We can get user feedback as to how they feel about this design proposal when implemented and through that feedback gathering insights and improving upon it.

**Comment by topotropic** [comment]
Thanks for the proposal! It's great that you explored what other browsers offer and described how you would approach the design.

**Comment by liuche** [comment]
@kglazko here's a download UX exploration from the UX intern. (you can also see that there's a "save PDF" issue above too!)

@topotropic how should we consider these UX explorations? Kate is currently working on Downloads and as we go through the user reviews, Downloads manager does come up pretty often (and for example, we've had a couple of people come through the Riot channel to ask about it).

Is this (or save page offline) something that we could build into nightly? or are these in the early phases and not intended to be built yet.

**Comment by topotropic** [comment]
@liuche this is exploration and needs to go through a design review again. 
Paging in @lime124 to consider it. Thanks!
