### ISSUE TITLE
Sync open tabs

### ISSUE THREAD

**Issue by areeshatariq** [mozilla-mobile/outreachy-UX-2020#56]
### What is the problem you are trying to solve?
[#5762](https://github.com/mozilla-mobile/fenix/issues/5762) Sync open tabs
### Why is it a problem?
Currently, a user can not access open tabs in other connected devices on Fenix. Work isn’t anchored to one device or one location. A user can be working on a desktop and using a smartphone as well. Thus, it is important that the user is able to access open tabs across devices.
### How would you solve the problem? What is your design proposal?
This problem will be solved by adding the feature of Sync tabs. Synced tabs will be displayed in the library. The user will be prompted to the Synced tabs page on clicking Synced tabs. There the user will be able to view opened tabs in other Fenix devices and will also have the options of:
- Manage devices (where all Fenix accounts can be viewed)
- Connect another device

## Design

<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77808470-4eaf8400-70ad-11ea-8e77-f7505d63ae79.jpg" width="50%" height="50%"></p>

### How would you measure your designs effectiveness?
The user should be efficiently able to:

- Sync tabs across Fenix connected devices
- Access synced tabs in other connected devices on Fenix
- Access synced Fenix tabs on other Fx connected devices

The implementation and use of the above features will show the design's effectiveness.
Users' feedback will help in working iteratively on design and improving it.

**Comment by topotropic** [comment]
Thanks for your proposal. I'm curious to learn if you considered other ways to access synced tabs besides of locating them in the library. Thanks!

> Synced tabs will be displayed in the library.

**Comment by areeshatariq** [comment]
@topotropic  we could add Synced tabs on the homepage as well. The user can access the synced tabs by clicking on the vertical elipses:
<p align="center"><img src="https://user-images.githubusercontent.com/24654457/79492490-828d2200-8039-11ea-9637-ce29dfd5396b.png" width="50%" height="50%"></p>
