### ISSUE TITLE
[Meta] Top Sites #6190

### ISSUE THREAD

**Issue by Vaishnavi-Reddy-Kancharla** [mozilla-mobile/outreachy-UX-2020#58]
**What is the problem you are trying to solve?**
[Meta] Top Sites
**Why is it a problem?**
Always adding most visited sites to top sites is problematic and it would be easier if they were added automatically to top sites. Especially if I’m connected to a particular site which does not have an app but I need to search it in a browser and especially when I visit such sites very often for an example my mess portal in my institute, then it would be very convenient to have those sites in my top sites. I wouldn't to add any site to my top site particularly but if we give users an option to add any particular site to top sites in the kebab menu icon then it would stand out compared to other browsers like chrome.

**How would you solve the problem? What is your design proposal?**
Have a space for top sites which is generally most visited sites but I wouldn't add any site to my top site particularly but if we give users an option to add any particular site to top sites in the kebab menu icon then it would be enough like its already present and that makes it stand out compared to other browsers like chrome. I don't think it’s essential to provide an add top site option near the top site area as it is generally obvious that your most frequent sites would be added automatically and if you want to add any site then there is an option too in kebab menu icon.
![91483204_584682408795044_1854446043802894336_n](https://user-images.githubusercontent.com/60965381/77827132-ee1a5880-7139-11ea-9a45-fdcaa18880e5.jpg)
![90987355_290863181880763_1651974237428121600_n](https://user-images.githubusercontent.com/60965381/77827139-f4103980-7139-11ea-8fdf-fd144d253231.jpg)

**How would you measure your designs effectiveness?**
It already exists in other browsers and it is very useful as it makes users go to their top sites quickly without them having to add it manually. I think this design is simple and useful.

**Comment by topotropic** [comment]
Thanks for the proposal!
