### ISSUE TITLE
Easy access to top share app -Rupali

### ISSUE THREAD

**Issue by Rupali2412** [mozilla-mobile/outreachy-UX-2020#59]
### What is the problem you are trying to solve?
User has been able to easily access the top sharing apps( frequently used apps ) to share web pages online.

### Why is it a problem?
The user might want to share a page without any complication as they might in between a job or chat, and complicated arrangement of apps options can distract them. Also, a distracting process might result in lost interest, ultimately effecting the browser's performance.

### How would you solve the problem? What is your design proposal?
1. Apps in share can be segregated into categories:

- social networking apps, devices, and other
- private sharing, stories and feed

This can allow the user to look through a selected category.

2. Using **down scrolling** to view all options to share the web page can be better as it can show all options on one page.

### How would you measure your design's effectiveness?
 If it helps the user to find the app easier than before. This can be tracked by observing how a user navigates through the apps in both UI.
Also, if the AI is possible to do so.

**Comment by topotropic** [comment]
Thanks for the proposal and good observation – attention can be very fragmented on mobile

> share a page without any complication as they might in between a job or chat
