### ISSUE TITLE
Voice input for Search #1216-Riya

### ISSUE THREAD

**Issue by riyasoganii** [mozilla-mobile/outreachy-UX-2020#60]
### What is the problem you are trying to solve?
Voice input for Search #1216
https://github.com/mozilla-mobile/fenix/issues/1216
### Why is it a problem?
I believe this feature would increase usability, especially when users may be visually impaired and thus struggling to type, or even when users are multitasking and would prefer to narrate their search rather than type it out.
### How would you solve the problem? What is your design proposal?
![Tabs (26)](https://user-images.githubusercontent.com/59031971/77843383-60328200-71ba-11ea-8db5-546d8d3ce514.png)
This button could be hidden on default but could be accessed in the settings under a menu called 'Accessibility'. This menu could include features such as narration in reader mode, night mode, voice input search, gestures, magnifying glass, etc. A very important part of any design is inclusivity-I believe these features should be experienced by all, regardless of any accessibility issues they might have. Thus, these features would be very important to add, to increase usability of all users.
I have proposed more solutions related to accessibility in the following issues, and if selected,I aim on making this one of the most important aspects to be focussed on in my design proposal.
https://github.com/mozilla-mobile/outreachy-UX-2020/issues/17
(Force web content to use dark mode)
https://github.com/mozilla-mobile/outreachy-UX-2020/issues/13
(Add narration feature to Reader Mode)

### How would you measure your designs effectiveness?
I believe this is a necessary feature as some keyboards do not support the text to speech concept. By making this feature optional in the accessibility menu it can be toggled by all.

**Comment by topotropic** [comment]
YES! Very well put. Thanks for your contribution.

> A very important part of any design is inclusivity-I believe these features should be experienced by all, regardless of any accessibility
