### ISSUE TITLE
Select text from hypertext link #1589-Riya

### ISSUE THREAD

**Issue by riyasoganii** [mozilla-mobile/outreachy-UX-2020#61]
### What is the problem you are trying to solve?
Select text from hypertext link #1589
https://github.com/mozilla-mobile/fenix/issues/1589
### Why is it a problem?
As a user, I don't have the option of selecting a section of a link- I can only copy the whole link. This might cause an issue when trying to slightly change the URL, or trying to search a specific part of the URL.
### How would you solve the problem? What is your design proposal?
Instead of the regular 'copy' option which pops up when long pressing a link, it can be changed to a 'select' option, which, when selected, default selects the whole link- but this can be adjusted by user, and then presents them with a copy option.
![Tabs (27)](https://user-images.githubusercontent.com/59031971/77843652-d0da9e00-71bc-11ea-871c-3da41af2b1da.png)

### How would you measure your designs effectiveness?
This is a necessary feature to increase ease of navigation. We could perform a user test where users are asked to select a specific part of the URL and observe whether of not they are able to perform this task intuitively and with ease.

**Comment by topotropic** [comment]
Thanks for the proposal. 

Did you consider keeping "Copy" as option and offering an "Select" as additional option? Why did you decide to remove "Copy" from the menu? Thanks!

**Comment by riyasoganii** [comment]
@topotropic I intended on introducing a copy option after selection as I thought it may be more straightforward to the user that way. 

In the scenario that a user was to use this feature to copy an _entire_ url, it might surprise them to see a select as well as copy option in the menu, and they might be confused as to what to select. Whereas, if there was only select, it would seem like the intuitive button for them to press. And since the feature default selects the entire URL, it reduces number of clicks for the user. 

In the second scenario, where a user was to use this feature to copy a _part_ of the URL, select is again the obvious option.

With continuous use of this feature, the gesture for selecting the URL(regardless of whether the user is selecting full or part of it) becomes intuitive only if it is uniform, and the user is consistently pressing the same buttons.

This was my reasoning behind the decision-however it is obviously a concern which can be tackled by user testing.
