### ISSUE TITLE
Deleting History and bookmarks([Meta] Gestures #176)-Riya

### ISSUE THREAD

**Issue by riyasoganii** [mozilla-mobile/outreachy-UX-2020#62]
### What is the problem you are trying to solve?
https://github.com/mozilla-mobile/fenix/issues/176
[Meta] Gestures #176
From this issue I will be tackling the sub issue of swiping left on a bookmark/history tab to delete.
### Why is it a problem?
As a user I would like an intuitive gesture to delete history and bookmarks. Especially since this feature has already been implemented for tabs, I consider it necessary to follow through with the same gestures across all pages of the app.
### How would you solve the problem? What is your design proposal?
I have already submitted a proposal to tackle the design issue of sharing tabs by swiping right, and deleting tabs by swiping left.
https://github.com/mozilla-mobile/outreachy-UX-2020/issues/37
In order to ensure consistency throughout my designs, and hence give the users an intuitive sense of gestures and their outcomes, I have decided to take a similar approach towards bookmarks and history tabs as well.
The history tabs/bookmarks can be SHARED by swiping right, and DELETED by swiping left.
![Tabs (28)](https://user-images.githubusercontent.com/59031971/77844266-f4084c00-71c2-11ea-8b7a-09ceeb9318c2.png)
![Tabs (29)](https://user-images.githubusercontent.com/59031971/77844268-f9fe2d00-71c2-11ea-887a-38ee5c09438f.png)
EDIT:
A new mechanism to select a certain set of entries to delete could also be introduced, apart from individual swipe-left deletion and complete deletion.
A trash icon could be introduced in the title bar, as so:
![Tabs (36)](https://user-images.githubusercontent.com/59031971/77919384-bd156180-72ba-11ea-8e8f-6cae20d223e5.png)
On clicking this icon, the user would be prompted if they would like to select certain items or delete all.
![Tabs (37)](https://user-images.githubusercontent.com/59031971/77919439-d0c0c800-72ba-11ea-894a-8be9a8c8dc51.png)
On clicking select, an empty checkbox will appear on the left of all entries. Subsequently, the trash icon in the header will turn red to indicate the implementation of the delete operation. The user can then select the items they would like to delete and then select the highlighted trash icon once again.
![Tabs (38)](https://user-images.githubusercontent.com/59031971/77919536-ee8e2d00-72ba-11ea-8d07-6d699dbab83c.png)
An alternate color scheme could be to color the check-box red rather than firefox purple, to highlight the activation of the delete feature and to match the highlighted trash icon:
![Tabs (39)](https://user-images.githubusercontent.com/59031971/77919669-1c737180-72bb-11ea-8997-7a180c44ee28.png)

### How would you measure your designs effectiveness?
In a user study we can ask the user to delete a bookmark and see if they choose the gesture route over the menu route. We then introduce them to both features and ask which one they would prefer.

**Comment by topotropic** [comment]
Thanks for the proposal! 

My assumption is that people expect to delete all their open tabs when they tap on the trash icon and would be surprised to get a menu – we could consider offering "Select" and "Delete history" as menu entries here – we also have a "Delete history" button at the top of the list.

**Comment by riyasoganii** [comment]
@topotropic That is a good point- users may be surprised to get a menu. Although I do think that providing two separate buttons to delete history might also get confusing for the user. Maybe this is an issue which could be worked on in user testing? Provided that the ability to select a group of items for deletion is necessary, which I think it is- else we could do with only the individual deletion and 'All' deletion.
