### ISSUE TITLE
Switch Tabs via Swiping Address Bar #3481-Riya

### ISSUE THREAD

**Issue by riyasoganii** [mozilla-mobile/outreachy-UX-2020#63]
### What is the problem you are trying to solve?
https://github.com/mozilla-mobile/fenix/issues/176
In this issue I will be tackling the sub issue of introducing a swiping gesture on the address bar to change tabs.
https://github.com/mozilla-mobile/fenix/issues/3481
### Why is it a problem?
As a user, I would like a uniform gesture across all apps to switch tabs. It is an intuitive action to swipe to switch tabs, and this gesture would also increase convenience of the user as they would not have to go back to the home page to switch tabs.
### How would you solve the problem? What is your design proposal?
I have come up with two design proposals. In both, the new tab entering the screen will enter in a very translucent color, and will become more and more opaque as the user continues to slide- until it becomes 100% opaque (when it covers the screen completely).
We could either go for the traditional route of sliding- where the tabs are circulated in a flat manner, as so:
![Tabs (30)](https://user-images.githubusercontent.com/59031971/77844883-e3a6a000-71c7-11ea-846d-4b8d5154f1b4.png)
Or, we could go for a new method which I have not yet seen- which is, when the user slides on the address bar, the actual address bar doesn't move- rather, only the new tab enters OVER the original tab(rather than sliding by its side), until it covers the old tab completely. Once this happens, the address bar is updated to show the respective new tab link.
![Tabs (31)](https://user-images.githubusercontent.com/59031971/77844940-49932780-71c8-11ea-820f-a3a9c17e3644.png)

### How would you measure your designs effectiveness?
On introducing a specific set of users to this gesture and asking them to browse on the app for a while, we can track the number of users which actually use this gesture intuitively compared to the number of users which go back to the tab menu to switch tabs.

**Comment by Gunkev** [comment]
Yes this way is modern and good too. But what about if user have a long list of open tabs and wish to go a a specific tab. I think the swiping will be too much and tiring than scrolling on the homepage. But I Iike the idea

**Comment by riyasoganii** [comment]
@Gunkev Thankyou for the feedback! I agree- this feature can only be used for recently accessed tabs :( . But it is an important one to include, nonetheless!
