### ISSUE TITLE
Swipe down on address bar to show home-Riya

### ISSUE THREAD

**Issue by riyasoganii** [mozilla-mobile/outreachy-UX-2020#64]
### What is the problem you are trying to solve?
https://github.com/mozilla-mobile/fenix/issues/176
Within this issue, I will provide a design solution for the sub issue "Swipe down on address bar to show home"
### Why is it a problem?
As a user, I would like an easier and more intuitive way of accessing the home page rather than clicking on the 'tabs' icon in the search bar.
### How would you solve the problem? What is your design proposal?
Depending on the implementability of this idea, I have come up with two design solutions-
In both design solutions, note that the open tab is becoming more and more translucent as the 'home' gesture is being pulled down further and further.
Design one-
![Tabs (32)](https://user-images.githubusercontent.com/59031971/77845308-844a8f00-71cb-11ea-943f-2e64fa4f960f.png)

Note: all designs provided can also be implemented in an alternate way, without the color.
![Tabs (33)](https://user-images.githubusercontent.com/59031971/77845313-90cee780-71cb-11ea-99d6-84f74215193d.png)

Note: As the bar is being pulled down, the tab beneath is becoming darker.
![Tabs (34)](https://user-images.githubusercontent.com/59031971/77845323-a9d79880-71cb-11ea-8971-7c1c8cbd71e5.png)

Once the user makes a gesture to swipe down completely and visit home, this black area covers the screen entirely and the home screen appears over it once loaded.

Design 2: If the implementation of this is possible, the home screen itself can be revealed more and more on swiping further down.

![Tabs (35)](https://user-images.githubusercontent.com/59031971/77845353-e3a89f00-71cb-11ea-9ce4-d0711a8ed19e.png)

### How would you measure your designs effectiveness?
On user testing we can introduce this feature to the users and monitor if they use this feature intuitively, to test the necessity of this gesture.

**Comment by Gunkev** [comment]
quite a good approach but I think you can also provide a way to tell the user that he should swipe in order to get to the home page

**Comment by riyasoganii** [comment]
@Gunkev Thanks for the input! As I had already proposed to @topotropic, I thought we could implement a one-time 'Whats new?' popup, which informs the user of the new features every time they install an update!
