### ISSUE TITLE
Choose to always open selected domains in reader mode - Rupali

### ISSUE THREAD

**Issue by Rupali2412** [mozilla-mobile/outreachy-UX-2020#65]
### What is the problem you are trying to solve?
User does not want to change the mode to reading each time for a particular domain.
https://github.com/mozilla-mobile/fenix/issues/6377

### Why is it a problem?
It causes data and time losses as the content is loaded twice. Also, every time changing mode when opening a website can be distracting.

### How would you solve the problem? What is your design proposal?
1. User when first time switching to reader's mode in a website have pop-option to always open in reader mode. User can turn-off mode temporarily from the sidebar menu. 
![Group 18](https://user-images.githubusercontent.com/60149380/77849809-e61af100-71eb-11ea-9c9d-550cf7018786.png)

2. User can disable reader view in settings 
![Group 21](https://user-images.githubusercontent.com/60149380/77850402-e61cf000-71ef-11ea-8c3d-ed7cd16b0b81.png)

### How would you measure your design's effectiveness?
1. An effective way is by analysing how many users are actually using the option to always switch to reader view. 
2. Also, tracking users who leave the website after seeing the dialogue box.

**Comment by topotropic** [comment]
Thanks for the proposal. A question in the original issue is 

> UX to recommend whether this should be a global toggle (always open in reader mode when available) or at the domain level whereby the user can specify to always load specific domains in reader mode.

What's your take here? Thanks

**Comment by Rupali2412** [comment]
Thanks for the feedback. @topotropic 
I think it can be made a global toggle (always open in reader mode when available) as it makes our browser accessible to everyone. 
For older adults, people with dyslexia or visual disability and even for people who want to enjoy reading without strain in their eyes changing reading mode for each domain can be an issue. 
Further, I will do research in this on people who are frequent reader's and what they prefer.

Edit: After casual discussion with the 3 potential users of the reader mode and found that 2 of them doesn't know about reader mode, they use night mode in their phone. 
Also globally opening webpages in reader mode, the webpages may lose their identity and look plain.
