### ISSUE TITLE
Make private browsing icon look more like a tappable button - Rupali 

### ISSUE THREAD

**Issue by Rupali2412** [mozilla-mobile/outreachy-UX-2020#66]
### What is the problem you are trying to solve?
Discoverability of private browsing button.
https://github.com/mozilla-mobile/fenix/issues/6334

### Why is it a problem?
User may not notice the button or misunderstand it with an icon( user thinking that firefox is always private ) which can defy the purpose of private browsing. 

### How would you solve the problem? What is your design proposal?
1.  A subtle shadow around the private browsing icon can increase it's visibility and can make it look like a **floating button.**
![private browsing](https://user-images.githubusercontent.com/60149380/77853766-86c8db00-7203-11ea-8816-17b7114422e5.png)

2. This shadow is of Mozilla UI style which also doesn't look awkward or grab more attention.

### How would you measure your design's effectiveness?
1. **A/B testing** - The more effective way is to compare clicks on private browsing button in both designs.   
2. **User observation** - It can also be effective to find issues facing while browsing.

**Comment by topotropic** [comment]
Thanks for the proposal!
