### ISSUE TITLE
Expand media menu

### ISSUE THREAD

**Issue by areeshatariq** [mozilla-mobile/outreachy-UX-2020#67]
### What is the problem you are trying to solve?
[#3621](https://github.com/mozilla-mobile/fenix/issues/3621) Add share option for images
### Why is it a problem?
Currently in Fenix, only the link of the image can be shared. To share an image, the user first has to save the image. There is no direct way of sharing an image with an application. 
### How would you solve the problem? What is your design proposal?
The user should have the option to share the image with an application directly from the Fenix mobile application. This will make it easier for the sender (to send the image) as well as the receiver to receive directly the image, not the URL.
#### Design

When the user long-presses an image, a pop-up appears as shown below. 

<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77861246-32d2ec00-722d-11ea-83de-1df32d771a39.jpg" width="50%" height="50%"></p>

When the user clicks on 'Share image', a pop-up appears where the user can share the image with the desired application.

<p align="center"><img src="https://user-images.githubusercontent.com/24654457/77861250-36ff0980-722d-11ea-8643-236e522827b2.jpg" width="50%" height="50%"></p>

### How would you measure your designs effectiveness?
It is a requested feature by the users and if the above feature is able to reduce the time to share an image (sender) and open the image (receiver), then the users will surely be using the feature.

**Comment by topotropic** [comment]
Sounds good, thanks for the proposal!
