### ISSUE TITLE
Opening a new tab from an existing tab and removing "+" from the main page.

### ISSUE THREAD

**Issue by Vaishnavi-Reddy-Kancharla** [mozilla-mobile/outreachy-UX-2020#69]
**What is the problem you are trying to solve?**
Opening a new tab from an existing tab and removing "+" from the main page.
**Why is it a problem?**
For opening a new tab from an existing tab in the current design, it's very confusing as there is no new tab option in the kebab menu and it takes us to the main page every time we want to open a new tab. It is also confusing because of one more reason as till we get very familiar with the browser we wouldn't know that by clicking on the switch tabs icon will take us back to the main page from where we can open a new tab.
**How would you solve the problem? What is your design proposal?**
I think an easier way to solve this problem is by adding a “+” sign beside the search bar and making users be able to open a new tab from the existing tab instead of taking users to the main page. And I also suggest removing the “+” sign from the main page for two reasons and the first reason is I really still not able to understand the main use of it because I was able to use another browser instead of google by just clicking on the search bar. The second reason is that the “+” sign actually confuses me that I will be able to open a new tab and that is not the case.
![91438325_523451831906755_6578945103451127808_n](https://user-images.githubusercontent.com/60965381/77877375-3be6ac00-7273-11ea-99f7-33760b5e1ea5.jpg)

**How would you measure your designs effectiveness?**
I have done a survey regarding this design and asked users to guess the functionality of  “+” beside the search bar. Majority of the responses were “open a new tab”

**Comment by topotropic** [comment]
Thanks for your feedback!
