### ISSUE TITLE
Switch Tabs via Swiping Address Bar #3481

### ISSUE THREAD

**Issue by Vaishnavi-Reddy-Kancharla** [mozilla-mobile/outreachy-UX-2020#70]
**What is the problem you are trying to solve?**
Switch tabs via swiping Address bar
 **Why is it a problem?**
It is a problem because every time I want to open a previous tab I have to go to the main page where there is a list of open tabs and select from that which is time-consuming.
**How would you solve the problem? What is your design proposal?**
I would like to present two design proposals 
1)when you swipe right it should show the tabs that are previously opened to the existing tab in the form of small cards where the entire tab is not open but a list of opened tabs with a search address and user can select from that and swipe left to see the tabs that were opened after the existing tab in the form of cards.
![91539403_459961781383418_1643421514432774144_n](https://user-images.githubusercontent.com/60965381/77882847-7d7d5400-727f-11ea-8bfc-589ea1b91fc1.jpg)
2)The second design idea is to go with the traditional method where the entire tab is loaded i.e if you swipe right then the previous tab would be loaded and if you swipe left then the tab which was opened after the existing tab would be loaded.
![switchtab](https://user-images.githubusercontent.com/60965381/77882861-8a01ac80-727f-11ea-82f5-86d77d4047d9.png)
 **How would you measure your designs effectiveness?**
open tabs is already an included feature in firefox android and making it is easier via swiping left and right instead of taking users to the main page would be great. The traditional method is a featured that has included in chrome already and has received a great response

**Comment by topotropic** [comment]
Thanks for the proposal, I like that you explored two possible designs to quicker switch tabs.
