### ISSUE TITLE
Review of FireFox App

### ISSUE THREAD

**Issue by khunsha965** [mozilla-mobile/outreachy-UX-2020#71]
### Name the three biggest issues
1. Extensive Scrolling on HomePage
2. Sharing Single Tabs with people (Functionality Disabled)
3. Collective History
[Outreachy-Problems in App.pptx](https://github.com/mozilla-mobile/outreachy-UX-2020/files/4401853/Outreachy-Problems.in.App.pptx)

### Explain why it’s an issue 
Please refer to the ppt file

### Show us how you would improve it
Please refer to the ppt file

### How would you measure your designs effectiveness?
1-Making prototype and testing on people by observing their first interaction with design.
2-Comparing the ease of use of my design with other browsers.
3-Taking reviews from other fellow designers.

**Comment by topotropic** [comment]
Thanks for the feedback!
