### ISSUE TITLE
UX improvemnet-Logo Size and Improvement

### ISSUE THREAD

**Issue by khunsha965** [mozilla-mobile/outreachy-UX-2020#73]
### Name the three biggest issues
1. Logo Size and Placement

### Explain why it’s an issue 
a) Size is unnecessarily big as compared to other visual elements(without any apparent usability)
b) Valuable space that can be utilized for sharing latest news,functionalities etc

Recommendation: Reduce the size and align to the top.

**Comment by topotropic** [comment]
Thanks for the proposal.
