### ISSUE TITLE
#2139 - Force Web content to use Dark Mode- Advika Singh

### ISSUE THREAD

**Issue by adi-1999** [mozilla-mobile/outreachy-UX-2020#74]
### What is the problem you are trying to solve?
Issue :- [#2139](https://github.com/mozilla-mobile/fenix/issues/2139)

### Why is it a problem?
A user when chooses the dark mode , might expect the browser to open all the other websites in dark mode for uniformity. Firefox Preview does not provide that option. The browser can be turned into dark mode , however the websites won't be. Dark Mode is essentially used to reduce the strain on the eyes, saves the battery of the mobile and because for some people the UI looks "cool" and better . If only the browser is in the dark mode and the website is not , The dark mode will not be able to fulfill its purpose.  

### How would you solve the problem? What is your design proposal?
I solved this problem by researching and reviewing the IA structure and competitive analysis (eg opera given below ). 

<img src="https://user-images.githubusercontent.com/58343952/77905687-52592b80-72a4-11ea-87be-cf483d7f3805.jpeg" alt="WhatsApp Image 2020-03-30 at 4 26 43 PM" width="250">

I tried to search up different features and tried to find out which features in dark mode themes are beneficial. However, to solve this problem a simple solution would suffice.  
When a user enables the dark mode , another option comes up to do the same for websites also. I feel there should also be a feature of  reading mode. The reading mode removes all the blue light, making sure there is less strain on the eye. Opera while providing this feature also provides a scale as to how much tint you want . However, that might be too complex for the user. Below is the design proposal.

<img src="https://user-images.githubusercontent.com/58343952/77906853-42dae200-72a6-11ea-84b9-8b8c09f2e6f1.jpeg" alt="WhatsApp Image 2020-03-30 at 4 42 40 PM (1)" width="250">
  
**Another Solution is developing add-ons** that darken the websites that the user can enable whenever they wish too.

### How would you measure your designs effectiveness?

**A/B Testing :** - Given the 2 options above , we can easily hold A/B testing as see which method would be more effective.
Putting in analytics (number of clicks) to see how much is the usage of these features and studying the data collected to bring the best feature out.
Reviews can also be an effective method to see the effectiveness of these features.
__

**Comment by topotropic** [comment]
Thanks for the proposal!
