### ISSUE TITLE
Download manager

### ISSUE THREAD

**Issue by Gunkev** [mozilla-mobile/outreachy-UX-2020#75]
### What is the problem you are trying to solve?
Download manager.
### Why is it a problem?
As a user I consider that a problem because sometimes when I download a file and later on when I want to access it I'm oblige to search in phone explorer which may take some time.
### How would you solve the problem? What is your design proposal?
As a designer I propose we add a download manager so that user can easily access any downloaded file and also offer the possibility to options. 

![download](https://user-images.githubusercontent.com/36812576/77915440-65adcc00-728f-11ea-875d-0ce3c9a93e2c.png)

### How would you measure your designs effectiveness?
1. As a design I will measure taking in account the efficiency and ease with which user access their files. An secondly I will use user feedback and survey as another tool.
2. Studying similar app and see their behavior is another way to measure design effectiveness
3. Ensure that my design follows the official design Principals.

**Comment by topotropic** [comment]
Thanks for the proposal!
