### ISSUE TITLE
Enable or disable Battery saver mode

### ISSUE THREAD

**Issue by Gunkev** [mozilla-mobile/outreachy-UX-2020#76]
### What is the problem you are trying to solve?
Battery saver mode
### Why is it a problem?
This is a problem because as a user I will like to save my battery if I encounter any household or battery problem. A user will like to navigate for a long period of time despite any problem. 
### How would you solve the problem? What is your design proposal?
As a designer I propose we add a battery saver mode options in parameters such that user can be able to control auto-play mode, loading high or low quality image, blocking trackers so as to save battery as much as possible. Here are some of my proposed interfaces.

![battery mode](https://user-images.githubusercontent.com/36812576/77916540-1d8fa900-7291-11ea-86d1-bd79a286bf6c.png)

### How would you measure your designs effectiveness?
I will measure effectiveness by
1. Working in close collaboration with the product manager and involving him in any design decisions.
2. By developing some prototypes at each design phase, testing with close as well as external collaborators and getting feedback.
3. Studying similar similar apps and see how the handle the issue in question.
3.Conducting survey, interviews and getting feedback from end users.
4. if possible working in close collaboration with a group of user so as to get to more understand their needs and desires.

**Comment by topotropic** [comment]
Interesting approach to bundle features under a user need instead of spreading them out in settings.
