### ISSUE TITLE
Narration mode in browser

### ISSUE THREAD

**Issue by Gunkev** [mozilla-mobile/outreachy-UX-2020#77]
### What is the problem you are trying to solve?
No Narration mode
### Why is it a problem?
This is a problem because as a user I don't like getting too much in contact with screens in order to prevent eye strains. Rather than reading an article especially a long article I rather have a narrator which takes care of that. I as a user can also be doing something else while listing to my article saving some time.
### How would you solve the problem? What is your design proposal?
1. As a designer I propose that we add a narrator mode in settings such that we offer possibility to user to turn it on if the wish to use the narrator. This really enhance user experience since they will not be forced to use it
2. If a user wishes to use the narrator he just switches it on and they can see it in their web page but if a user does not want to use it he switches it off so he won't see it in his browser. Below is an interface showing different transitions

![narration mode](https://user-images.githubusercontent.com/36812576/77921721-0a340c00-7298-11ea-9fa6-14ec7a45cd05.png)

### How would you measure your designs effectiveness?
1. First of all I will develop prototypes following design principles and test them in and out of the team in order to get feedback.
2. Another tool is to work in close collaboration with users
3. Conducting a feasibility study see what is done and read critics in order not to reproduce the same errors.
4.Getting feedback from user and the team as a whole

**Comment by topotropic** [comment]
Thanks for the proposal.
