### ISSUE TITLE
#3262- Pull to refresh webpage- Advika Singh

### ISSUE THREAD

**Issue by adi-1999** [mozilla-mobile/outreachy-UX-2020#80]
### What is the problem you are trying to solve?
issue :- [#3262](https://github.com/mozilla-mobile/fenix/issues/3262)

### Why is it a problem?
Pulling down to refresh tab is a feature that provides quick and easy usability. This feature is lacking in the app . Incorporating this feature would enhance user experience
### How would you solve the problem? What is your design proposal?
Competive analysis would be a good way to tackle this problem. Chrome and opera mini both make the user go to the top and then pull down to refresh. While chrome uses a rotation blue circle to indicate refresh opera mini use cogs to as an icon of refresh.
**Chrome:-**
<img src="https://user-images.githubusercontent.com/58343952/77950465-28c0f400-72e6-11ea-91ef-cd579128e0ca.jpeg" alt="WhatsApp Image 2020-03-31 at 12 23 51 AM" width="250">

**Opera Mini:-**

<img src="https://user-images.githubusercontent.com/58343952/77950517-3aa29700-72e6-11ea-8503-1b66541862dd.jpeg" alt="WhatsApp Image 2020-03-31 at 12 23 45 AM" width="250">

So we have 2 options :- 
1) the user scrolls to the top and then pulls down to refresh.
2) the user pulls down right below the bar menu to refresh. 
**The user should atleast pull down 1/8th of the screen from the top in order to refresh. The UI will appear at 1/8 of the screen from the top.**
**UI for refresh:-**

**1st option:-**

![unnamed_1](https://user-images.githubusercontent.com/58343952/77954926-041c4a80-72ed-11ea-8ba4-79b3678e956c.gif)

**2nd option:-**

![unnamed](https://user-images.githubusercontent.com/58343952/77954954-10080c80-72ed-11ea-95b7-afc7e208ba57.gif)

### How would you measure your designs effectiveness?
Analytics as to how much will the refresh API will be called which will tell us the importance of this feature .

**Comment by liuche** [comment]
Hey @adi-1999, I think @Mugurell has an apk with a demo of this ready, in this PR https://github.com/mozilla-mobile/fenix/pull/9440 . You should be able to download it (see instructions in comment 0), and then you can do a design review/test it out before it lands.

Also feel free to reach out to him on Slack (Petru) or Riot.

**Comment by adi-1999** [comment]
Hey **@liuche** ,
Hope you are doing well.
Yes, I would love to review/test it and I will definitely be reaching out to him.

**Comment by topotropic** [comment]
Thanks for your contribution! 

Here's a quick video https://drive.google.com/file/d/1USVgp8IirznWWJoYPi6XPETdROYYxzTQ/view 
You can also find an apk here https://firefox-ci-tc.services.mozilla.com/tasks/bgx9Ny3ySHu3tZmtP3aXFw#artifacts

**Comment by adi-1999** [comment]
> Hey @adi-1999, I think @Mugurell has an apk with a demo of this ready, in this PR [mozilla-mobile/fenix#9440](https://github.com/mozilla-mobile/fenix/pull/9440) . You should be able to download it (see instructions in comment 0), and then you can do a design review/test it out before it lands.
> 
> Also feel free to reach out to him on Slack (Petru) or Riot.

Hello @liuche ,
As suggested, I have reviewed the new Firefox Nightly app and the link for the same is :-
[#112](https://github.com/mozilla-mobile/outreachy-UX-2020/issues/112)
Thank you!
