### ISSUE TITLE
Bookmarks, collections and Hick's law

### ISSUE THREAD

**Issue by sunidhi-kashyap** [mozilla-mobile/outreachy-UX-2020#81]
### What is the problem you are trying to solve?
The existence of both "**collections**" and "**bookmarks**" increases complexity and it takes longer for the user to make a decision, when it comes to saving a site for future use.

### Why is it a problem?
**Hick's Law** states that the time required for a user to make a decision increases with the number and complexity of choice available. So basically the more choices you have or the harder the choices are, the longer it takes for your user to make a decision.

The existence of both "**collections**" and "**bookmarks**" increases complexity and it takes longer for the user to make decision, when it comes to saving a site for future use.

Let’s say a user visits a site and wants to save it for later use. In Firefox Preview, user has bookmarks and collections. By **Hick’s Law**, the complexity increases.
The user here has 2 options, which is not a lot. But looking closely, the interaction involves multiple steps. Which increases the number of tasks.

### How would you solve the problem? What is your design proposal?
To solve the problem, as a user we must ask ourselves 2 questions : 
1) Do I really need both of them?
2) Which one is better, "**collections**" or "**bookmarks**"?

To find this out I ran a **usability test** on an average college student. I asked him to make 2 different folders and add one-one websites each, 1st using "**collections**" and then using "**bookmarks**", and I timed both the processes.

The results : 
Using collections : about 1 min
Using bookmarks : about 3 mins

So, the ratio of time taken is, 1:3. It takes three times more time to do the same task using **bookmarks**, as it does using **collections**.

Then asked the user, above 2 questions and his response were;
1)No, he didn't feel like he needed both of them.
2)He found **collections** better, given that making a new folder on **bookmarks** was "**really confusing and frustrating**".

So, a good design will be removing the **bookmarks** option. 

### How would you measure your designs effectiveness?

This design will be effective because;
a)A user won't be confused when wanting to save a website for future use.
b)He will straightaway go for the **collections**, since it is in the homepage and adding a website to the **collections** is way more _discoverable and intuitive_, compared to the **bookmarks** option.
c)When a user already has "**collections**", he would not even think of using **bookmarks**.
d)**Collections** make Firefox Preview unique and user friendly.

**Comment by topotropic** [comment]
Thanks for the contribution. I really liked your explanation and quick hallway test you documented here.

**Comment by sunidhi-kashyap** [comment]
> Thanks for the contribution. I really liked your explanation and quick hallway test you documented here.

Thankyou so much for your appreciation! It keeps me motivated to do more.
