### ISSUE TITLE
The browsing mode remains private after quitting

### ISSUE THREAD

**Issue by sunidhi-kashyap** [mozilla-mobile/outreachy-UX-2020#96]
The private browsing is supposed to fulfill every purpose that a user expects from it. Which includes not just hiding his private search history, but not giving out hints that he was browsing privately, as a local attacker comes in.

**Problem  :**
Fenix remains on the private browsing mode even after the user quits.
![Group 103](https://user-images.githubusercontent.com/42182441/78472685-7a3f0800-7758-11ea-920d-3d13e1dce6ff.png)

**Solution :** 
The mode should switch to the normal browsing mode after the user quits the app.

**Effectiveness :**
A user expects the app to switch from private browsing mode to regular mode after closing the app.

**Comment by topotropic** [comment]
Thanks for the proposal and the visualization!

**Comment by sunidhi-kashyap** [comment]
Thanks for the encouragement !
